### ISSUE TITLE
Please add Biometric authentication to unlock molly

### ISSUE THREAD

**Issue by aravind-alpha07** [mollyim/mollyim-android#100]
### Is there an existing request for this?

- [X] I have searched the existing issues

### Feature description

Hey team please add Biometric authentication (fingerprint) to unlock molly.. everytime I need to type passphrase to unlock sometimes it's annoying & sometimes it's uncomfortable. I can't able to type the passphrase infront of everyone in public transport so please consider this and add the biometric authentication feature.

**Comment by valldrac** [comment]
This feature is already in the backlog https://github.com/mollyim/mollyim-android/issues/94
