### ISSUE TITLE
Power button press while taking a photo database-locks Molly

### ISSUE THREAD

**Issue by flippflapp** [mollyim/mollyim-android#101]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

Molly's database encryption is enabled, with an auto lock timeout of 2hrs. 

When I want to take a picture from within Molly and press the power button while within the camera, my phone locks. After unlocking the phone, Molly is locked as well. This happens when I want to take a photo from within an individual chat or from the chat overview pane. It does not coincide with the auto lock timeout. 

I am running GrapheneOS. Molly runs not within the owner profile, but within a user profile.

### Steps to reproduce

1. Enable database encryption.
2. Press the camera symbol from the chat overview or from within a chat.
3. Press the power button.
4. Unlock phone.

### Molly version

v5.34.9-2-FOSS

### Android version

Android 12

### Device

Google Pixel 4a

### Link to debug log

https://debuglogs.org/android/5.34.9/7d24053d01c63b9c0f473bf80129ac1b89d4f827fb73428af8ba78e53ba651cc

**Comment by Seb3thehacker** [comment]
I have Molly installed on my main profile on Lineage OS, Android 11. Followed you steps to reproduce the bug and it locked for me as well. Mine is also set to never lock automatically.

**Comment by valldrac** [comment]
Fixed in 96c8ecb9902cfe9c7ac8e615b660ad1bbdbefaca
