### ISSUE TITLE
Multi Device 

### ISSUE THREAD

**Issue by xyz-nobody** [mollyim/mollyim-android#102]
### Is there an existing request for this?

- [X] I have searched the existing issues

### Feature description

A long time ago a signal fork existed which allowed to have a real multi device on Android. 

Could you reintegrate this fork into Molly? The protocol allows it, it would be necessary that when we install Molly we can flash a QR CODE (like on signal desktop) and hop our android is in slave mode.

https://github.com/andrewmattie/Signal-Android-Multidevice

**Comment by pr0927** [comment]
So am I correct in understanding that currently there is no multi-device support - like with Signal and syncing to a PC?

**Comment by Chromatros** [comment]
You can sync molly to your PC

**Comment by pr0927** [comment]
Oh, O.K., awesome, thanks!

**Comment by masonwilliaml** [comment]
This was recently discussed on Matrix but as a unique implementation for Molly. With upcoming Android tablets (eg Pixel Tablet on GrapheneOS), it would be nice to have Molly on both the phone and tablet. To enable this, the Android app would have to be modified to support being a linked device (in addition to the primary device). Hopefully this can be implemented once the current projects are completed.

**Comment by nospace-here** [comment]
Signal might be adding tablet support on their own, thanks to Google https://community.signalusers.org/t/android-version-of-signal-now-available-on-tablets-and-chromeos/54570/7

**Comment by valldrac** [comment]
Completed in #157
