### ISSUE TITLE
No molly option on default app select

### ISSUE THREAD

**Issue by samuraikid0** [mollyim/mollyim-android#107]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

No molly on default app selection on Lineage OS
![Screenshot_20220503-074056_Permission_controller](https://user-images.githubusercontent.com/46766062/166521806-ed2057d6-c77b-43d7-ad0f-a1216d599de1.png)

### Steps to reproduce

1.
2.

### Molly version

v5.34.9-2 foss

### Android version

Android 10

### Device

Samsung S7

**Comment by valldrac** [comment]
Molly does not support SMS/MMS like Signal does. For that reason it cannot be setup as default messaging app in Android.
