### ISSUE TITLE
Add Material You with dynamic theming

### ISSUE THREAD

**Issue by Paulanerus** [mollyim/mollyim-android#112]
### Is there an existing request for this?

- [X] I have searched the existing issues

### Feature description

Android 12 introduced wallpaper based dynamic color theming with material you and it would be so great to have an option to enable and apply this to the whole app theme

**Comment by ayaen** [comment]
I think this would be nice to have upstream too?

**Comment by ayaen** [comment]
Are you aware of any developments on their end in their forum. Meanwhile I search myself.
I think the changes might be too invasive for Molly to support it all by itself. 
In the end it's up to valldrac.

**Comment by Paulanerus** [comment]
> Are you aware of any developments on their end in their forum. Meanwhile I search myself. 
> 
> 
> 
> I think the changes might be too invasive for Molly to support it all by itself. 
> 
> In the end it's up to valldrac.

Sadly i don't know how to do this since i don't have any experience in android development. And yes, this might be too invasive for Thais Kind of project, i agree with that.But it would be nice to support at least the dynamic icons introduced in android 13. As far as i know this should be pretty easy to implement.

https://developer.android.com/about/versions/13/features#themed-app-icons

**Comment by valldrac** [comment]
Signal is already working on this and Molly will adopt the changes as always. The transition to Material You will start in the next release 5.41. I think it will probably span one or two releases more until complete because it is a huge redesign.
