### ISSUE TITLE
Please update the reproducible-builds tutorial

### ISSUE THREAD

**Issue by JuniorWolfgamingDE** [mollyim/mollyim-android#115]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

Some commands of the reproducible-builds step-by-step documentation in this repo aren't up2date.
This makes it hard to reproduce everything.
Please update!

### Steps to reproduce

1. Go through the commands which are listed here: https://github.com/mollyim/mollyim-android/tree/main/reproducible-builds
2. At this command: 
python apkdiff/apkdiff.py Molly-$VERSION.apk apks/prodNonFree/release/Molly-prod-unsigned-$VERSION.apk
You will see an error message because the file output is now somewhere else.

### Molly version

v5.24.17.1

**Comment by valldrac** [comment]
Thanks for reporting it.

Indeed the paths changed after the version 5.24.17-1 and the tutorial reflects the correct paths. If you try to reproduce the latest version of Molly (5.42.8-2) the tutorial work.

If you really want to test v5.24.17-1 you should follow the instructions contained in the file README of that version, after running git checkout.
