### ISSUE TITLE
Crash at startup after v5.44.3: could not decrypt 'pref_unidentified_access_certificate_rotation_time'

### ISSUE THREAD

**Issue by realbiz21** [mollyim/mollyim-android#116]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

After upgrading to 5.44.3-1 August 3, 2022, molly doesn't open anymore and Android shows that Molly keeps stopping. All is seen is the purple splash screen for a few seconds, then it crashes.

The primary reason seems to be:

> SignalUncaughtException: java.lang.SecurityException: Could not decrypt 'pref_unidentified_access_certificate_rotation_time' value. MAC doesen't match.

logcat shows this stack trace:

```
E SignalUncaughtException: java.lang.SecurityException: Could not decrypt 'pref_unidentified_access_certificate_rotation_time' value. MAC doesen't match.
E SignalUncaughtException: 	at org.thoughtcrime.securesms.crypto.EncryptedPreferences.decrypt(EncryptedPreferences.java:449)
E SignalUncaughtException: 	at org.thoughtcrime.securesms.crypto.EncryptedPreferences.getDecryptedObject(EncryptedPreferences.java:374)
E SignalUncaughtException: 	at org.thoughtcrime.securesms.crypto.EncryptedPreferences.getLong(EncryptedPreferences.java:283)
E SignalUncaughtException: 	at org.thoughtcrime.securesms.util.TextSecurePreferences.getLongPreference(TextSecurePreferences.java:1039)
E SignalUncaughtException: 	at org.thoughtcrime.securesms.util.TextSecurePreferences.getUnidentifiedAccessCertificateRotationTime(TextSecurePreferences.java:623)
E SignalUncaughtException: 	at org.thoughtcrime.securesms.service.RotateSenderCertificateListener.getNextScheduledExecutionTime(RotateSenderCertificateListener.java:19)
E SignalUncaughtException: 	at org.thoughtcrime.securesms.service.PersistentAlarmManagerListener.onReceiveUnlock(PersistentAlarmManagerListener.java:22)
E SignalUncaughtException: 	at org.thoughtcrime.securesms.service.ExportedBroadcastReceiver.onReceive(ExportedBroadcastReceiver.java:14)
E SignalUncaughtException: 	at org.thoughtcrime.securesms.service.RotateSenderCertificateListener.schedule(RotateSenderCertificateListener.java:33)
E SignalUncaughtException: 	at org.thoughtcrime.securesms.ApplicationContext.initializePeriodicTasks(ApplicationContext.java:488)
```

### Steps to reproduce

1. Upgrade to 5.44.3-1 from version 5.42.8-2
2. Run Molly (or reboot phone since Molly runs at startup)

### Molly version

v5.44.3-1-FOSS

### Android version

Android 12, GrapheneOS

### Device

Pixel 3a

**Comment by signus** [comment]
I too can confirm a very similar issue on a Pixel 3a with GrapheneOS (Android12) began occurring after the update from `v5.42.8-2-FOSS` to `v5.44.3-1-FOSS`.

However, based on my interaction this does not occur during startup in my instance, but during the selection of a conversation (denoted by `ConversationActivity` being displayed in the following logcat output), however the SecurityException in this instance is for `pref_media_keyboard_mode`, but still an inability to decrypt due to a mismatched MAC:

```
08-05 14:02:57.845  1146  1174 I ActivityTaskManager: Displayed im.molly.app/org.thoughtcrime.securesms.conversation.ConversationActivity: +1s187ms
08-05 14:02:57.859  7002  7002 I ExoPlayerImpl: Release 431f4e0 [ExoPlayerLib/2.15.0] [sargo, Pixel 3a, Google, 32] [goog.exo.core, goog.exo.mediasession]
08-05 14:02:57.876  7002  7002 I ConversationParentFragm: onModified(RecipientId::78) REGISTERED
08-05 14:02:57.886  7002  8046 E BpDisplayEventConnection: Failed to transact (-9)
08-05 14:02:57.887  7002  7002 D AndroidRuntime: Shutting down VM
08-05 14:02:57.900  7002  7002 E AndroidRuntime: FATAL EXCEPTION: main
08-05 14:02:57.900  7002  7002 E AndroidRuntime: Process: im.molly.app, PID: 7002
08-05 14:02:57.900  7002  7002 E AndroidRuntime: java.lang.SecurityException: Could not decrypt 'pref_media_keyboard_mode' value. MAC doesen't match.
08-05 14:02:57.900  7002  7002 E AndroidRuntime: 	at org.thoughtcrime.securesms.crypto.EncryptedPreferences.decrypt(EncryptedPreferences.java:449)
08-05 14:02:57.900  7002  7002 E AndroidRuntime: 	at org.thoughtcrime.securesms.crypto.EncryptedPreferences.getDecryptedObject(EncryptedPreferences.java:374)
08-05 14:02:57.900  7002  7002 E AndroidRuntime: 	at org.thoughtcrime.securesms.crypto.EncryptedPreferences.getString(EncryptedPreferences.java:251)
08-05 14:02:57.900  7002  7002 E AndroidRuntime: 	at org.thoughtcrime.securesms.util.TextSecurePreferences.getStringPreference(TextSecurePreferences.java:1023)
08-05 14:02:57.900  7002  7002 E AndroidRuntime: 	at org.thoughtcrime.securesms.util.TextSecurePreferences.getMediaKeyboardMode(TextSecurePreferences.java:946)
08-05 14:02:57.900  7002  7002 E AndroidRuntime: 	at org.thoughtcrime.securesms.conversation.ConversationParentFragment.lambda$initializeStickerObserver$39(ConversationParentFragment.java:2209)
08-05 14:02:57.900  7002  7002 E AndroidRuntime: 	at org.thoughtcrime.securesms.conversation.ConversationParentFragment.$r8$lambda$-e6OXJ-qVhwsB-Rn3AKdpMQ7-Rc(Unknown Source:0)
08-05 14:02:57.900  7002  7002 E AndroidRuntime: 	at org.thoughtcrime.securesms.conversation.ConversationParentFragment$$ExternalSyntheticLambda99.onChanged(Unknown Source:4)
08-05 14:02:57.900  7002  7002 E AndroidRuntime: 	at androidx.lifecycle.LiveData.considerNotify(LiveData.java:133)
08-05 14:02:57.900  7002  7002 E AndroidRuntime: 	at androidx.lifecycle.LiveData.dispatchingValue(LiveData.java:151)
08-05 14:02:57.900  7002  7002 E AndroidRuntime: 	at androidx.lifecycle.LiveData.setValue(LiveData.java:309)
08-05 14:02:57.900  7002  7002 E AndroidRuntime: 	at androidx.lifecycle.MutableLiveData.setValue(MutableLiveData.java:50)
08-05 14:02:57.900  7002  7002 E AndroidRuntime: 	at androidx.lifecycle.LiveData$1.run(LiveData.java:93)
08-05 14:02:57.900  7002  7002 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:938)
08-05 14:02:57.900  7002  7002 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
08-05 14:02:57.900  7002  7002 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:201)
08-05 14:02:57.900  7002  7002 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:288)
08-05 14:02:57.900  7002  7002 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7876)
08-05 14:02:57.900  7002  7002 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
08-05 14:02:57.900  7002  7002 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
08-05 14:02:57.900  7002  7002 E AndroidRuntime: 	at com.android.internal.os.ExecInit.main(ExecInit.java:48)
08-05 14:02:57.900  7002  7002 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
08-05 14:02:57.900  7002  7002 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:355)
08-05 14:02:57.900  7002  7002 E AndroidRuntime: Caused by: java.security.GeneralSecurityException: MAC doesen't match.
08-05 14:02:57.900  7002  7002 E AndroidRuntime: 	at org.thoughtcrime.securesms.crypto.MasterCipher.verifyMacBody(MasterCipher.java:148)
08-05 14:02:57.900  7002  7002 E AndroidRuntime: 	at org.thoughtcrime.securesms.crypto.MasterCipher.decrypt(MasterCipher.java:106)
08-05 14:02:57.900  7002  7002 E AndroidRuntime: 	at org.thoughtcrime.securesms.crypto.EncryptedPreferences.decrypt(EncryptedPreferences.java:447)
08-05 14:02:57.900  7002  7002 E AndroidRuntime: 	... 22 more
08-05 14:02:57.902  7002  7002 E SignalUncaughtException: java.lang.SecurityException: Could not decrypt 'pref_media_keyboard_mode' value. MAC doesen't match.
08-05 14:02:57.902  7002  7002 E SignalUncaughtException: 	at org.thoughtcrime.securesms.crypto.EncryptedPreferences.decrypt(EncryptedPreferences.java:449)
08-05 14:02:57.902  7002  7002 E SignalUncaughtException: 	at org.thoughtcrime.securesms.crypto.EncryptedPreferences.getDecryptedObject(EncryptedPreferences.java:374)
08-05 14:02:57.902  7002  7002 E SignalUncaughtException: 	at org.thoughtcrime.securesms.crypto.EncryptedPreferences.getString(EncryptedPreferences.java:251)
08-05 14:02:57.902  7002  7002 E SignalUncaughtException: 	at org.thoughtcrime.securesms.util.TextSecurePreferences.getStringPreference(TextSecurePreferences.java:1023)
08-05 14:02:57.902  7002  7002 E SignalUncaughtException: 	at org.thoughtcrime.securesms.util.TextSecurePreferences.getMediaKeyboardMode(TextSecurePreferences.java:946)
08-05 14:02:57.902  7002  7002 E SignalUncaughtException: 	at org.thoughtcrime.securesms.conversation.ConversationParentFragment.lambda$initializeStickerObserver$39(ConversationParentFragment.java:2209)
08-05 14:02:57.902  7002  7002 E SignalUncaughtException: 	at org.thoughtcrime.securesms.conversation.ConversationParentFragment.$r8$lambda$-e6OXJ-qVhwsB-Rn3AKdpMQ7-Rc(Unknown Source:0)
08-05 14:02:57.902  7002  7002 E SignalUncaughtException: 	at org.thoughtcrime.securesms.conversation.ConversationParentFragment$$ExternalSyntheticLambda99.onChanged(Unknown Source:4)
08-05 14:02:57.902  7002  7002 E SignalUncaughtException: 	at androidx.lifecycle.LiveData.considerNotify(LiveData.java:133)
08-05 14:02:57.902  7002  7002 E SignalUncaughtException: 	at androidx.lifecycle.LiveData.dispatchingValue(LiveData.java:151)
08-05 14:02:57.902  7002  7002 E SignalUncaughtException: 	at androidx.lifecycle.LiveData.setValue(LiveData.java:309)
08-05 14:02:57.902  7002  7002 E SignalUncaughtException: 	at androidx.lifecycle.MutableLiveData.setValue(MutableLiveData.java:50)
08-05 14:02:57.902  7002  7002 E SignalUncaughtException: 	at androidx.lifecycle.LiveData$1.run(LiveData.java:93)
08-05 14:02:57.902  7002  7002 E SignalUncaughtException: 	at android.os.Handler.handleCallback(Handler.java:938)
08-05 14:02:57.902  7002  7002 E SignalUncaughtException: 	at android.os.Handler.dispatchMessage(Handler.java:99)
08-05 14:02:57.902  7002  7002 E SignalUncaughtException: 	at android.os.Looper.loopOnce(Looper.java:201)
08-05 14:02:57.902  7002  7002 E SignalUncaughtException: 	at android.os.Looper.loop(Looper.java:288)
08-05 14:02:57.902  7002  7002 E SignalUncaughtException: 	at android.app.ActivityThread.main(ActivityThread.java:7876)
08-05 14:02:57.902  7002  7002 E SignalUncaughtException: 	at java.lang.reflect.Method.invoke(Native Method)
08-05 14:02:57.902  7002  7002 E SignalUncaughtException: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
08-05 14:02:57.902  7002  7002 E SignalUncaughtException: 	at com.android.internal.os.ExecInit.main(ExecInit.java:48)
08-05 14:02:57.902  7002  7002 E SignalUncaughtException: 	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
08-05 14:02:57.902  7002  7002 E SignalUncaughtException: 	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:355)
08-05 14:02:57.902  7002  7002 E SignalUncaughtException: Caused by: java.security.GeneralSecurityException: MAC doesen't match.
08-05 14:02:57.902  7002  7002 E SignalUncaughtException: 	at org.thoughtcrime.securesms.crypto.MasterCipher.verifyMacBody(MasterCipher.java:148)
08-05 14:02:57.902  7002  7002 E SignalUncaughtException: 	at org.thoughtcrime.securesms.crypto.MasterCipher.decrypt(MasterCipher.java:106)
08-05 14:02:57.902  7002  7002 E SignalUncaughtException: 	at org.thoughtcrime.securesms.crypto.EncryptedPreferences.decrypt(EncryptedPreferences.java:447)
08-05 14:02:57.902  7002  7002 E SignalUncaughtException: 	... 22 more
08-05 14:02:58.173  7002  7002 I JobManager: Successfully flushed.
```

I will see what else I can uncover, and if I find what I have found is significantly different than OP I will create a new issue. It should be noted that as it stands this means Molly is unusable for anyone who runs into this problem.

**Comment by CJones217** [comment]
I have the same issue on 5.44.3-1 as @signus 

``` type: crash osVersion: google/barbet/barbet:12/SQ3A.220705.004/2022080900:user/release-keys package: [im.molly.app:109700](javascript:void(0)) process: [im.molly.app](http://im.molly.app/) java.lang.SecurityException: Could not decrypt 'pref_media_keyboard_mode' value. MAC doesen't match. at org.thoughtcrime.securesms.crypto.EncryptedPreferences.decrypt([EncryptedPreferences.java:449](http://encryptedpreferences.java:449/)) at org.thoughtcrime.securesms.crypto.EncryptedPreferences.getDecryptedObject([EncryptedPreferences.java:374](http://encryptedpreferences.java:374/)) at org.thoughtcrime.securesms.crypto.EncryptedPreferences.getString([EncryptedPreferences.java:251](http://encryptedpreferences.java:251/)) at org.thoughtcrime.securesms.util.TextSecurePreferences.getStringPreference([TextSecurePreferences.java:1023](http://textsecurepreferences.java:1023/)) at org.thoughtcrime.securesms.util.TextSecurePreferences.getMediaKeyboardMode([TextSecurePreferences.java:946](http://textsecurepreferences.java:946/)) at org.thoughtcrime.securesms.conversation.ConversationParentFragment.lambda$initializeStickerObserver$39([ConversationParentFragment.java:2209](http://conversationparentfragment.java:2209/)) at org.thoughtcrime.securesms.conversation.ConversationParentFragment.$r8$lambda$-e6OXJ-qVhwsB-Rn3AKdpMQ7-Rc(Unknown Source:0) at org.thoughtcrime.securesms.conversation.ConversationParentFragment$$ExternalSyntheticLambda99.onChanged(Unknown Source:4) at androidx.lifecycle.LiveData.considerNotify([LiveData.java:133](http://livedata.java:133/)) at androidx.lifecycle.LiveData.dispatchingValue([LiveData.java:151](http://livedata.java:151/)) at androidx.lifecycle.LiveData.setValue([LiveData.java:309](http://livedata.java:309/)) at androidx.lifecycle.MutableLiveData.setValue([MutableLiveData.java:50](http://mutablelivedata.java:50/)) at androidx.lifecycle.LiveData$1.run([LiveData.java:93](http://livedata.java:93/)) at android.os.Handler.handleCallback([Handler.java:938](http://handler.java:938/)) at android.os.Handler.dispatchMessage([Handler.java:99](http://handler.java:99/)) at android.os.Looper.loopOnce([Looper.java:201](http://looper.java:201/)) at android.os.Looper.loop([Looper.java:288](http://looper.java:288/)) at [android.app](http://android.app/).ActivityThread.main([ActivityThread.java:7876](http://activitythread.java:7876/)) at java.lang.reflect.Method.invoke(Native Method) at [com.android](http://com.android/).internal.os.RuntimeInit$MethodAndArgsCaller.run([RuntimeInit.java:548](http://runtimeinit.java:548/)) at [com.android](http://com.android/).internal.os.ExecInit.main([ExecInit.java:48](http://execinit.java:48/)) at [com.android](http://com.android/).internal.os.RuntimeInit.nativeFinishInit(Native Method) at [com.android](http://com.android/).internal.os.RuntimeInit.main([RuntimeInit.java:355](http://runtimeinit.java:355/)) at [[ ↑↑ Original Trace ↑↑ ]].(:0) at [[ ↓↓ Exception Message ↓↓ ]].(:0) at Could not decrypt 'pref_media_keyboard_mode' value. MAC doesen't match..(:0) Caused by: [java.security](http://java.security/).GeneralSecurityException: MAC doesen't match. at org.thoughtcrime.securesms.crypto.MasterCipher.verifyMacBody([MasterCipher.java:148](http://mastercipher.java:148/)) at org.thoughtcrime.securesms.crypto.MasterCipher.decrypt([MasterCipher.java:106](http://mastercipher.java:106/)) at org.thoughtcrime.securesms.crypto.EncryptedPreferences.decrypt([EncryptedPreferences.java:447](http://encryptedpreferences.java:447/)) at org.thoughtcrime.securesms.crypto.EncryptedPreferences.getDecryptedObject([EncryptedPreferences.java:374](http://encryptedpreferences.java:374/)) at org.thoughtcrime.securesms.crypto.EncryptedPreferences.getString([EncryptedPreferences.java:251](http://encryptedpreferences.java:251/)) at org.thoughtcrime.securesms.util.TextSecurePreferences.getStringPreference([TextSecurePreferences.java:1023](http://textsecurepreferences.java:1023/)) at org.thoughtcrime.securesms.util.TextSecurePreferences.getMediaKeyboardMode([TextSecurePreferences.java:946](http://textsecurepreferences.java:946/)) at org.thoughtcrime.securesms.conversation.ConversationParentFragment.lambda$initializeStickerObserver$39([ConversationParentFragment.java:2209](http://conversationparentfragment.java:2209/)) at org.thoughtcrime.securesms.conversation.ConversationParentFragment.$r8$lambda$-e6OXJ-qVhwsB-Rn3AKdpMQ7-Rc(Unknown Source:0) at org.thoughtcrime.securesms.conversation.ConversationParentFragment$$ExternalSyntheticLambda99.onChanged(Unknown Source:4) at androidx.lifecycle.LiveData.considerNotify([LiveData.java:133](http://livedata.java:133/)) at androidx.lifecycle.LiveData.dispatchingValue([LiveData.java:151](http://livedata.java:151/)) at androidx.lifecycle.LiveData.setValue([LiveData.java:309](http://livedata.java:309/)) at androidx.lifecycle.MutableLiveData.setValue([MutableLiveData.java:50](http://mutablelivedata.java:50/)) at androidx.lifecycle.LiveData$1.run([LiveData.java:93](http://livedata.java:93/)) at android.os.Handler.handleCallback([Handler.java:938](http://handler.java:938/)) at android.os.Handler.dispatchMessage([Handler.java:99](http://handler.java:99/)) at android.os.Looper.loopOnce([Looper.java:201](http://looper.java:201/)) at android.os.Looper.loop([Looper.java:288](http://looper.java:288/)) at [android.app](http://android.app/).ActivityThread.main([ActivityThread.java:7876](http://activitythread.java:7876/)) at java.lang.reflect.Method.invoke(Native Method) at [com.android](http://com.android/).internal.os.RuntimeInit$MethodAndArgsCaller.run([RuntimeInit.java:548](http://runtimeinit.java:548/)) at [com.android](http://com.android/).internal.os.ExecInit.main([ExecInit.java:48](http://execinit.java:48/)) at [com.android](http://com.android/).internal.os.RuntimeInit.nativeFinishInit(Native Method) at [com.android](http://com.android/).internal.os.RuntimeInit.main([RuntimeInit.java:355](http://runtimeinit.java:355/)) ```

running on latest version of GrapheneOS. 
What I remember happening is swiping on the side of my screen to back out of the conversation I was in and then the app crashing. Sorry for not having more detail

**Comment by Graph3n** [comment]
Same here it crashed and now when open just logo it does not open for whatsoever.

Could help if same version to just repudiate itself so we can use it.

Before next version comes out and we use normally idea would be just to make device think same version is new version and it will work probably and later when update it will work

**Comment by tuxiqae** [comment]
I'm seemingly suffering from the same issue after updating to `v5.44.3-1-FOSS` on GrapheneOS

**Comment by Seb3thehacker** [comment]
Molly (FOSS) runs fine my Pixel 6 with GrapheneOS. Possibility just a 3a issue?

**Comment by tuxiqae** [comment]
@Seb3thehacker 
Nope, happens to me on Google Pixel 6 Pro

**Comment by tuxiqae** [comment]
Thank you @valldrac !

**Comment by valldrac** [comment]
The root cause was a concurrency bug in the encryption of the preferences values. This code was written by Signal almost 10 years ago for local storage encryption and it is not thread-safe. Signal is not affected by this bug because they stopped using the local encryptor class when they removed the passphrase encryption. However, Molly still uses it. In the last release there was an performance improvement (https://github.com/signalapp/Signal-Android/commit/9c914ab71) that basically share the object that calls this encryptor across the app, and thus multiple threads may hit the non-thread-safe code.

The concurrency bug is fixed and clean installation of the incoming release should work fine. 

For users running 5.44.3-1 the corrupted preferences will be reset to default values. This should allow the app to back to normal in most but not all the cases where the app hangs.

**Comment by tuxiqae** [comment]
Approved working
