### ISSUE TITLE
Molly is able to take photo in landscape when it shouldn't be

### ISSUE THREAD

**Issue by flippflapp** [mollyim/mollyim-android#119]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

When having "auto-rotate" disabled, i.e. the OS does not allow the screen to be oriented in landscape, Molly will still switch to landscape view after I tapped the camera icon from within Molly (doesn't matter whether it's from the chat overview or from within a chat) and rotated my phone. This does _not_ happen when not taking a picture.

~~This is especially weird as I did not grant Molly the "Sensors" permission which I thought should prevent Molly to be able to get information from the phone's gyroscope to determine the phone's orientation in the first place. But this might be a misunderstanding on my side?~~ ([thanks for clarifying!](https://github.com/mollyim/mollyim-android/issues/119#issuecomment-1218352365))

### Steps to reproduce

1. Disable "auto-rotate" in the OS settings.
2. Attempt to take a photo from within Molly.
3. Rotate the phone into physical landscape orientation.

Actual result:
Molly will rotate into landscape view.

Expected result:
Molly should respect the OS setting and stay in portrait view.

### Molly version

v5.44.5-1-FOSS

### Android version

Android 12, GrapheneOS SQ3A.220705.004.2022080900

### Device

Google Pixel 4a

### Link to debug log

https://debuglogs.org/android/5.44.5/e6ef8fbd19299cebae9aa66f52834af4e2210fe17f0eea6852286eff11cd52a8

**Comment by thestinger** [comment]
Disabling Sensors access means the app gets no data from sensors such as accelerometers and gyroscopes. It has no impact on the OS screen rotation API which doesn't involve the app accessing sensors.

**Comment by valldrac** [comment]
Photo in Landscape is working like it works with Signal now. Fixed in pre-release 5.50.4-1.
