### ISSUE TITLE
DuckDuckGo's Tracking Protection reported a tracking attempt

### ISSUE THREAD

**Issue by Grkrz** [mollyim/mollyim-android#122]
### Is there an existing request for this?

- [X] I have searched the existing issues

### Feature description

![Screenshot_20220818-224428](https://user-images.githubusercontent.com/107203983/185492110-f2b7e921-c60e-422f-ba12-a48377197430.png)
![Screenshot_20220818-224441](https://user-images.githubusercontent.com/107203983/185492274-355023a8-80aa-4285-9bfb-cf9753d94bb0.png)

**Comment by valldrac** [comment]
It is a false positive. There is no tracking technology in Molly.

Maybe It was triggered when the app generated the preview of a web link posted in a chat. Or it could the app reporting this is simply inaccurate.

**Comment by Grkrz** [comment]
Apology from my site!

**Comment by bell-kevin** [comment]
Interesting. I wonder if I'm getting a similar issue with the DuckDuckGo Android app. collecting false positive on the NewPipe app.
