### ISSUE TITLE
Implement an option to ignore remote deletion?

### ISSUE THREAD

**Issue by dhammel** [mollyim/mollyim-android#123]
Hello,

As title states, can you implement an option to ignore remote deletion when done by another user using the option "Delete for everyone"? (Turned off by default)

**Comment by revuwa** [comment]
I would love to see this feature in Molly, too.

I found a project named: [Signal-JW](https://github.com/johanw666/Signal-Android) ([GPLv3 licensed](https://github.com/johanw666/Signal-Android/blob/main/LICENSE)) which includes exactly that feature.
It seems to put a bunch of features directly on top of Signal upstream, with commit: [Added extra options](https://github.com/johanw666/Signal-Android/commit/a7f171a67e4150cc827418992a582faa72103d68) from where the following features (relevant for this) could be cherry-picked:

- Option to treat view-once media as normal media.
- Option to ignore remote deletion.
- Option to delete only the media from a message, not the rest of the message.

The equivalent extra (added) preferences should be:

- val keepViewOnceMessages: Boolean,
- val ignoreRemoteDelete: Boolean,
- val deleteMediaOnly: Boolean,

and looks like this (in their patched app): 
![image](https://user-images.githubusercontent.com/7300276/188277680-3c123b84-4cbb-49b0-9405-4463ca76dcc7.png)
Source: from the [project's page](https://johanw.home.xs4all.nl/Signal/signal-jw.html).

**Comment by johanw666** [comment]
I have already talked about that with Valldrac and he does not like the idea. You can of course always patch it into Molly, I do so myself: https://github.com/johanw666/mollyim-android

**Comment by revuwa** [comment]
@johanw666 
Thanks for the reply and the reference to your patched Molly repo.
I don't suppose you offer the ready to go apk for download- or better via an F-Droid repo, (for automatic updates)?

**Comment by johanw666** [comment]
I could send an apk but I don't have an F-Droid repo.

**Comment by revuwa** [comment]
> I could send an apk but I don't have an F-Droid repo.

Thanks a lot for that offer, but my (and for sure other's) problem would be, how to (automatic) update the patched app, then?
Would you possibly consider to create/run a repo, like the [patched-apps](https://thecapslock.gitlab.io/fdroid-patched-apps/fdroid/repo/) one, or would it probably be a viable way for @valldrac to provide a patched molly flavor?

**Comment by flippflapp** [comment]
> I have already talked about that with Valldrac and he does not like the idea. 

Then close this isssue as `wontfix` or sth. like this?

**Comment by valldrac** [comment]
I believe it's better for the project to follow Signal's rules while connecting to their servers, even if I don't like key decisions they made about remote deletion.

As a workaround, it shouldn't be hard to patch the code in your own Github repository to add those features. Custom builds can be easily automated. Molly already uses Docker and GitHub actions extensively.
