### ISSUE TITLE
Set Molly as the default messaging app in Android.

### ISSUE THREAD

**Issue by martijnw1986** [mollyim/mollyim-android#125]
### Is there an existing request for this?

- [X] I have searched the existing issues

### Feature description

Signal can be set to be the default messaging app for Android. I just recently switched to Molly but I cannot find it in the default app selection.

**Comment by esonique** [comment]
I also just ran into this issue too. I only see the option for messages. 
Android 13
Pixel 6

**Comment by valldrac** [comment]
Molly does not support SMS/MMS like Signal does. For that reason it cannot be setup as default messaging app in Android.

**Comment by turboyz** [comment]
maybe is it time to plan this integration with SMS?
