### ISSUE TITLE
Even after refreshing, new contacts don't show up.

### ISSUE THREAD

**Issue by chisbroad** [mollyim/mollyim-android#129]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

Once you click the pencil icon in the bottom right and refresh the contact list, it should show new contacts who have also installed Signal or its fork but it doesn't happen with me.

I have already given it the permission for contacts, microphone, camera, and phone.

Also, thank you so much for everything you all are doing. I really appreciate it.

### Steps to reproduce

1.
2.

### Molly version

v5.48.3-1-FOSS

### Android version

Android 12 (S1SR32.38-124-3)

### Device

Moto G52

### Link to debug log

https://debuglogs.org/android/5.48.3/84422aa1fe12dd48a7003cbb590d293f8dcbba76c4f142793fa334d784d458ac

**Comment by chisbroad** [comment]
Now that you mention it, I tried another Signal fork Langis but the problem persisted there as well.

It didn't work; I even deleted my account. Can you please suggest what should I do next?

**Comment by valldrac** [comment]
Please reopen this issue if the problem still persist after a clean install. As the last resort, you can try the official app and contact Signal support.
