### ISSUE TITLE
Molly-foss will crash after using a few days

### ISSUE THREAD

**Issue by Raj2032** [mollyim/mollyim-android#131]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

After using a few days of Molly, I would keep getting a message from Android that Molly has crashed.

I have reinstalled it, it has worked after a few days however it still crashes.

I imported from Signal's backup. I will now attempt to use it without using Signal's backup.

### Molly version

Molly-v5.48.3-1-FOSS.apk

### Android version

9

### Device

Samsung galaxy S8

**Comment by valldrac** [comment]
Would you be able to try to use adb to get the logs? And email me support@molly.im

https://developer.android.com/studio/command-line/adb

**Comment by Raj2032** [comment]
@valldrac Yep sure if it screws up again I can help you out :)
