### ISSUE TITLE
Location sharing shows blank map and doesnt find the location

### ISSUE THREAD

**Issue by liennero** [mollyim/mollyim-android#132]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Bug description

![screenshot_29092022](https://user-images.githubusercontent.com/101482409/193036875-dbc82338-afe8-4dfc-9fb2-9a745e68a354.png)

When I try to share my location, it just shows me a blank map and doesnt find my location. Molly has location access granted. GPS is turned on, and location requests are rerouted to the location service provided by graphene os.
This feature does work on signal for me with the completely same settings.

### Steps to reproduce

1.
2.

### Molly version

v5.50.4-1

### Android version

Android 13

### Device

Google Pixel 5

### Link to debug log

https://debuglogs.org/android/5.50.4/3356ffdde3110feeb4b25e666a76857f42fff4bbb7a92d47638c340e48e32c7a

**Comment by valldrac** [comment]
Also https://github.com/mollyim/mollyim-android/commit/5b34b001b02cba7a37f8ece5e8823b088a2868c8
