### ISSUE TITLE
My recordes voice messages are VERY quiet

### ISSUE THREAD

**Issue by TalOrenshtein** [mollyim/mollyim-android#133]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

When I'm recording a voice message, the message itself is very quiet. It works fine in other apps and I know the feature itself can works fine because when my friend recorded a message, I heard him just fine.

### Steps to reproduce

1.record a voice message.
2.

### Molly version

v5.50.4-1-FOSS

### Android version

10

### Device

Xiaomi mi 9t, using lineage os.

### Link to debug log

https://debuglogs.org/android/5.50.4/84a2d28ce2cde81a0eceea62dff4e3bc64cdc8f40b3ffbb255bd4c6445d1c740

**Comment by valldrac** [comment]
This ticket is from a really old version. This bug is already fixed.
