### ISSUE TITLE
Retain SMS/MMS Support

### ISSUE THREAD

**Issue by deadpoint** [mollyim/mollyim-android#137]
### Is there an existing request for this?

- [X] I have searched the existing issues

### Feature description

Signal is planning on removing SMS/MMS support in an upcoming release. This existing feature is very valuable to many users around the world, please continue to support this feature.

https://community.signalusers.org/t/signal-blog-removing-sms-support-from-signal-android-soon/47954

**Comment by flippflapp** [comment]
Molly never supported it in the first place and will not add support for an inherently unsafe protocol that deserves to be forgotten forever.
