### ISSUE TITLE
SMS/MMS Maintain?

### ISSUE THREAD

**Issue by seniorm0ment** [mollyim/mollyim-android#138]
Will Molly be able to maintain SMS/MMS support which Signal is deciding to unfortunately remove? There is a large amount of people upset about this, and a fork would be needed to maintain this feature. Molly seems like it could be the next best option currently?
Many people want unification with their messaging app, this removal means more fragmentation and users will need two different apps.
https://signal.org/blog/sms-removal-android/

**Comment by valldrac** [comment]
Molly never supported SMS. It was removed in the first release because it was incompatibility with the security improvements.
