### ISSUE TITLE
Use OpenStreetMap as location provider

### ISSUE THREAD

**Issue by valldrac** [mollyim/mollyim-android#14]

**Comment by iiitomo** [comment]
Probably code from signal-foss can be reused , see https://forum.f-droid.org/t/ive-degoogled-signal-messenger/10443/76

**Comment by valldrac** [comment]
Seems it was too early to set it as done. There are some issues to work on before it's ready to release.

- Move tile database to cachedir
- Encrypt tile database
- Set proxy settings
- Check for DNS leaks when the proxy is configured

I've moved the development of this feature to an experimental branch.

**Comment by carallo** [comment]
Is it possible to use OSM as location provider but still using Google's FCM as push notification provider? I am on microg and have issues with Google Maps provider, but still need FCM due to battery draining...

BTW, thank you so much for your work!

**Comment by valldrac** [comment]
Yes. Google Maps is going to be replaced by OSM in both Molly and Molly-FOSS. Remember that the standard version Molly already uses FCM.

There are some issues we have to fix first. See my comment above.

**Comment by carallo** [comment]
> Yes. Google Maps is going to be replaced by OSM in both Molly and Molly-FOSS. Remember that the standard version Molly already uses FCM.
> 
> There are some issues we have to fix first. See my comment above.

Perfect, thank you so much! 
I know standard Molly version uses FCM, but being on microg location sharing does not work with Google Maps provider, so I wanted to try OSM version to see if it fixes the issue, but I still need FCM.
I will be waiting till OSM gets implemented, thank you again and good luck!

**Comment by ronidee** [comment]
Can the OSM lib or API used as a drop-in replacement for the Google version? 
At least moxie said he'd be (or was..) open to merge a PR if this would work, iirc.

**Comment by MrCybertux** [comment]
@valldrac i do not know if this helps you but the guys over at telegram FOSS have a working implementation of OSM
https://github.com/Telegram-FOSS-Team/Telegram-FOSS

**Comment by baarkerlounger** [comment]
@valldrac the readme still refers to Molly-Foss not supporting a location provider. Is it correct to say it now does?

**Comment by valldrac** [comment]
> @valldrac the readme still refers to Molly-Foss not supporting a location provider. Is it correct to say it now does?

Nice catch! I need to update the README.
