### ISSUE TITLE
Add time for screen lock

### ISSUE THREAD

**Issue by JohnBetaro** [mollyim/mollyim-android#143]
### Is there an existing request for this?

- [x] I have searched the existing issues

### Feature description

It will be very handy feature to set a time for locking molly with fingerprint rather than default locking it instantly when exit, because every time it locks i can't read the messages from the notifications i have to unlock it again and again, i know you maybe did this to add more privacy and security but at least you can bring it back and maybe set the timer for instant lock by default, it's about having a choice.

I think this feature is already implemented in the original signal app  so maybe you can just add it again, because at this time there is no solution but leaving the app unlocked by default.

I hope you'll consider my thoughts on this and thank you for your time.

**Comment by flippflapp** [comment]
In our Matrix room the user "Voxel" expressed their support for this feature request! Apparently, setting a timer for screen lock is still part of the vanilla Signal client so presumably it should not be too involved to implement this?

I wonder why this issues was closed?
