### ISSUE TITLE
Restoring backup with passphrase let to write only numbers

### ISSUE THREAD

**Issue by TalOrenshtein** [mollyim/mollyim-android#145]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

Restoring backup with passphrase let to write only numbers. It's even pops you out the keyboard that has numbers only. I can't restore now because my passphrase uses,for example, letters too.

### Steps to reproduce

1.Use a passphrase with letters for example
2.back up your data
3. Delete molly
4. Try to restore

### Molly version

v5.52.5-2-FOSS

### Link to debug log

No log when you're logged out.

**Comment by valldrac** [comment]
The passphrase to lock Molly that you set up at installation, and the password for backups, they are different things. When you enable backups in Settings > Chat, the app will tell you to write down the password for backups, that is composed by only numbers randomly generated.

**Comment by TalOrenshtein** [comment]
Oh alright, tnx.
