### ISSUE TITLE
Voice message record is very week

### ISSUE THREAD

**Issue by TalOrenshtein** [mollyim/mollyim-android#146]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

When I'm sending a voice message, the voice message itself is very week comparing to any other app that can send a voice message (signal app included)

### Steps to reproduce

1.
2.

### Molly version

Version 5.52.5-2-FOSS

### Link to debug log

https://debuglogs.org/android/5.52.5/bfa2e819dc1753d70e659dc91648b5898b6310ff24b629a99d3b420f19dd70ce

**Comment by valldrac** [comment]
This ticket is from a really old version. This bug is already fixed.
