### ISSUE TITLE
Suggestion: Backup to WebDAV

### ISSUE THREAD

**Issue by Trident589** [mollyim/mollyim-android#149]
### Is there an existing request for this?

- [X] I have searched the existing issues

### Feature description

The scoped storage feature that is currently provided in molly never works quite right for me. It always leads to the files being deleted by another app that is trying to back the files up to my cloud (in my case its the nextcloud app). Being able to upload the backup using WebDAV would solve this problem. I know that this is a feature not a lot of people would use, but I'm sure it would help out at least some people a lot.

Even if you do not add it, thank you for the great work you are doing here, have a nice day.

**Comment by HyperCriSiS** [comment]
What also would help a lot are incremental backups, because Signal DBs can get quite huge.
Unfortunately the Signal devs seem not too have much interest to change this anytime soon. :(

Best regards
Hyper
