### ISSUE TITLE
[Question/Feature Request] SMS/MMS Support

### ISSUE THREAD

**Issue by grravity** [mollyim/mollyim-android#15]
Was curious about the removal of SMS/MMS. I notice it is stated it is for compatibility reasons, however I am curious if this was a quick thing to work-around, or it is genuinely not possible?

Would be extremely nice to see SMS/MMS supported, as it is very nice to not be required to utilize two seperate apps for that. 

Is this something that could be worked on perhaps?

**Comment by valldrac** [comment]
There were some issues when Signal and Molly were installed on the same device. But honestly, I don't remember the details. I can only tell you that it didn't seem trivial to fix.

Molly is focused on security. It's true that now it offers more functionality not strictly related to security. But still, it's the main reason to release Molly.

SMS are insecure and can be easily intercepted. Should a secure app, that claims to be more secure than Signal under certain conditions, to support unencrypted communications? I don't think so. On the other hand, there are probably better SMS apps than Signal. With two apps, the boundary between what is secure and what is not is easier for the user to discern, than if everything fits into a single app.

There were minors factors that also helped me to remove SMS: the app is smaller, the attack surface is smaller too, and there are less code to maintain (less merge conflicts).

**Comment by grravity** [comment]
I completely agree that SMS is an insecure protocol, however that is mainly the case when using SMS, not using Signal protocol. You still utilize the Signal protocol when messaging other Signal users, however you don't lose the ability to utilize SMS where it may be needed (as not everyone uses Signal, and people can be stubborn). In my personal opinion, the fact that Signal supports SMS/MMS was a _major_ benefit as it negated the need to use two separate apps (For Signal and SMS) and could be used as a single messaging app. 

As for smaller attack surface, this is completely understandable, as is the desire to have less code to maintain to avoid issues.
The latter is why I am hesitant to suggest, however still will, maybe adding a third branch (Preferably off of Molly-FOSS) that still continues SMS/MMS support if possible. 

I see no major reason to have Molly and Signal on the same device, except for dual numbers, so if this is the major conflict with introducing SMS/MMS as you may think, maybe this could be the tradeoff of the third branch (Only allow the branch including SMS/MMS but lose the ability to have both Signal and Molly). Because you can't have both Signal and Molly registered under the same number anyways.

The introduction of Google Services is what really bothers me about Signal, and is why I personally found high interest in your fork, alongside the other tweaks and additions. However the lack of SMS/MMS support within Molly-FOSS has made it preferably unusable from a convenience stance in my case, and I'm sure I'm not the only one who feels this way as I have heard others appreciate the SMS/MMS integration within Signal.

It would be amazing if this could be looked at again, and hopefully introduced, however I understand and respect your reasons not to. 
Thank you.

**Comment by valldrac** [comment]
I think I remember what is the major blocker to support SMS. It is incompatible with the Molly password lock.

The default SMS app is responsible of storing the messages and notifying the user at the time a new SMS is received. The problem is that when Molly is locked, the database is unavailable (more details here). Not only the database, but also the configuration. In that state, Molly would not be able to handle any SMS and the messages would be lost. I am afraid that to solve this, a full re-design is needed.

If you don't need the security features, there are more projects apart from Molly that have degoogled Signal. As far as I know [Langis](https://langis.cloudfrancois.fr) and [tw-hx's fork](https://github.com/tw-hx/Signal-Android/).

**Comment by viasux** [comment]
> I think I remember what is the major blocker to support SMS. It is incompatible with the Molly password lock.
> 
> The default SMS app is responsible of storing the messages and notifying the user at the time a new SMS is received. The problem is that when Molly is locked, the database is unavailable (more details [here](https://github.com/mollyim/mollyim-android/issues/13#issuecomment-696646034)). Not only the database, but also the configuration. In that state, Molly would not be able to handle any SMS and the messages would be lost. I am afraid that to solve this, a full re-design is needed.
> 
> If you don't need the security features, there are more projects apart from Molly that have degoogled Signal. As far as I know [Langis](https://langis.cloudfrancois.fr) and [tw-hx's fork](https://github.com/tw-hx/Signal-Android/).

I do sincerely hope that this is possible to fix in molly sometime in the future, possibly a separate db for mms that isn't encrypted? - I appreciate the suggestion for alternatives though, thank you!
