### ISSUE TITLE
No sound on Bluetooth headphones in call

### ISSUE THREAD

**Issue by FinchRelia** [mollyim/mollyim-android#151]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

When having a call with someone while being connected to my Bluetooth headphones the sound doesn't go in the headphones but rather goes through the phone speakers instead. There is no option on the UI to chose where the sound should goes through. Also, this configuration was working perfectly when I used Signal and not Molly before. I don't often make Molly calls on my phone but I have also experimented this issue with previous versions of Molly-FOSS.

### Steps to reproduce

1. Connect my phone to Bluetooth headphones
2. Make a Molly call with someone (user or group)

### Molly version

v.5.52.5-2-FOSS

### Android version

Android 12 (GrapheneOS)

### Device

Pixel 3a

**Comment by valldrac** [comment]
This ticket is from a really old version. This bug is already fixed.
