### ISSUE TITLE
Molly Crashes When Opening Notification Settings

### ISSUE THREAD

**Issue by Ao1Pointblank** [mollyim/mollyim-android#155]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

When trying to fine-tune notifications in the in-app notifications settings menu, the app will freeze and crash
I am using GrapheneOS on a Pixel 5

### Steps to reproduce

1.restart phone
2.open molly
3.menu at top right > Settings > Notifications
4.app instantly freezes

at this stage, you have 2 choices, a and b.

5a.press circle button to close app
6a.after a while, android sends a prompt to quit the app or wait. waiting does not help and the prompt repeats. this is what i consider a crash.

or:

5b.stay in the app. touch nothing. the notifications menu eventually opens after ~40sec
6b. change settings as you like. each change takes another 40sec or so
### Molly version

v6.3.6-1-FOSS

### Android version

Android 13, Graphene OS (build TQ1A.221205.011)

### Device

Google Pixel 5

### Link to debug log

https://debuglogs.org/android/6.3.6/8daacb898e368bbd115218ddd4df68c2b6ff45dff7e45b5c9595992cab27ae7f

**Comment by Ao1Pointblank** [comment]
New Debug Log
https://debuglogs.org/android/6.3.6/f6ff9c382b121389ea05af373d18638fc95b97dfd3bf2bbda81a2675aa0439e2

**Comment by valldrac** [comment]
Sorry, but I missed this issue. And now the debug logs have already been deleted, since the server keeps them only for 30 days.

If you experience this issue again, please reopen the ticket. I think I found the possible cause of the app freezes, but would need a debug log to confirm.

**Comment by valldrac** [comment]
Thank you. Did you see the app freeze before saving the debug log? The log spans only one minute.

**Comment by Ao1Pointblank** [comment]
yes it did definitely freeze, but probably only about a minute. i can make a screenrecording if you want it?
