### ISSUE TITLE
Keep SMS support (since signal stops it)

### ISSUE THREAD

**Issue by hirntot** [mollyim/mollyim-android#159]
### Is there an existing request for this?

- [X] I have searched the existing issues

### Feature description

Hi there!
Since [Signal announced](https://signal.org/blog/sms-removal-android/) that they'd stop SMS support, I am looking for a fork that supports at least Signal and SMS also in the future - maybe even threema and telegram as well (why not? wouldn't that be great, to have one app that supports all four protocols?).

So the question for you: will you (at least) keep on supporting SMS?

greets
hirntot

**Comment by lberrymage** [comment]
Hi! Molly actually removed SMS support a long time ago (before Signal announced their decision) because it's incompatible with its security features. I don't believe there are any plans to add it back.

**Comment by hirntot** [comment]
ok, sorry to hear. thanks for the fast answer...

**Comment by kosssi** [comment]
Too bad, SMS is a standard and consumes less energy (I don't have a reliable source, but if you think otherwise and you have a source, I'm interested)

I was just looking for the opposite option to always be able to go through SMS rather than the Internet... I'll stay on Silence.im then.
