### ISSUE TITLE
[Features] Read description

### ISSUE THREAD

**Issue by pixincreate** [mollyim/mollyim-android#163]
### Is there an existing request for this?

- [X] I have searched the existing issues

### Feature description

I'm newbie in Android development and I build Signal on my [repo](https://github.com/pixincreate/Signal) with some added features.  
I went through #123, #71 to see if you support them ad I learnt that you don't.   
My build currently supports the below features (I've customised these to my own taste since I use it personally):
- Enabled some feature flags
- Only arm64-v8a build
- Different signing key (for personal use)
- Automatically fetch updates and Build on GH Actions automatically.
- Option to choose between FCM or WebSocket for notification delivery
- Option to ignore remote delete and view-once-messages
- Option to select who can add you to group

If you're willing to takes patches, I can put up a PR that includes: 
- Enabled some feature flags
- Automatic fetch updates (you can customise it)
- Build on GH Actions after fetching from upstream (you can customise it)
- Option to choose between FCM or WebSocket for notification delivery
- Option to select who can add you to group

**Comment by valldrac** [comment]
@pixincreate First of all, it's great that you're interested in contributing to Molly development! However, after reviewing your suggestions, I found that these patches are not necessary.

But don't worry, there are plenty of other ways you can still get involved and gain experience. We have some issues labeled as "help wanted" in our issue tracker, and if those seem too advanced for you, you can still contribute by improving the documentation, writing tests, or helping with testing.

Another option is to participate in discussions in our dev room [#mollyim-testing:matrix.org](https://matrix.to/#/#mollyim-testing:matrix.org), where you can ask questions, share your thoughts, and learn from more experienced developers.
