### ISSUE TITLE
Please add OpenStreetMap as Location provider in Molly-FOSS

### ISSUE THREAD

**Issue by jakecharlie** [mollyim/mollyim-android#169]
### Is there an existing request for this?

- [X] I have searched the existing issues

### Feature description

Hello, I saw on the comparison page between the three versions: Molly-FOSS, Molly and Signal that Molly-FOSS does not have Google Maps as Location provider, however an alternative was not inserted in its place
https://github.com/mollyim/mollyim-android

I suggest to Molly developers another Signal fork called Signal-FOSS that did just that and is also open source:
https://www.twinhelix.com/apps/signal-foss/
https://github.com/tw-hx/Signal-Android
The Signal-FOSS version uses OpenStreetMap instead of Google Maps. Please consider this possibility as well.

You can look at how they implemented OpenStreetMap and implemented it in Molly-FOSS as well

**Comment by BHydden** [comment]
I don't know where I read it but pretty sure this is already planned. 👍

**Comment by valldrac** [comment]
It's planned indeed. See #14.
