### ISSUE TITLE
Require database encryption passphrase for Screen Security

### ISSUE THREAD

**Issue by alizair** [mollyim/mollyim-android#172]
### Is there an existing request for this?

- [X] I have searched the existing issues

### Feature description

If molly's database is protected with a passphrase then require that passphrase for enabling or disabling screen security.

**Comment by valldrac** [comment]
Thank you for submitting your feature request. Can you please elaborate on why screen security is considered an important setting that requires a passphrase input, when compared to other settings?

**Comment by alizair** [comment]
After thinking about this, I do think you have a point. I thought about how screenshots could be used in a malicious way by someone gaining access to my device through any means, but preventing screenshots would not do much in that case, because they would already have access to all of my chats in an unencrypted form, in the first place.

Thank you for your reply.
