### ISSUE TITLE
Safety number cannot be viewed

### ISSUE THREAD

**Issue by ProgrammerWhoPrograms** [mollyim/mollyim-android#178]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

On only one conversation, when I go to see the safety number, I get a popup saying "You must first exchange messages in order to view ${person}'s safety number". I have exchanged messages with that person.

### Steps to reproduce

1.
2.

### Molly version

v6.17.3-1-FOSS

### Android version

Android 13

### Device

Google Pixel 6a

### Link to debug log

https://debuglogs.org/android/6.17.3/83827e54bb98ccce75e9078669f31a870cd172b1723c598e9a40b1d88a77c29a

**Comment by valldrac** [comment]
There was a bug in Signal. It should be fixed in Molly v6.18.4-1.

I'm not sure if the safety number will show up again after updating for already failed chats. Maybe the contact needs to send a message to you to make it work.

**Comment by ProgrammerWhoPrograms** [comment]
The safety number shows up now. Thank you.
