### ISSUE TITLE
Set Custom Polling Time

### ISSUE THREAD

**Issue by cm157** [mollyim/mollyim-android#18]
I use GrapheneOS which is a de-googled and hardened fork of Android in conjunction with Molly-IM. 

Since it does not have google play services I believe Signal will set a manual polling time to 15min to fetch in the background pending messages. 

If it's not difficult would you be able to implement an option that allows for alternative (I.e. 5min) or custom polling time in some future release?

**Comment by valldrac** [comment]
The notifications should arrive intermediately. There is no such polling time. Signal keeps keeps the websocket connection to the server open all the time. It sends pings every minute to keep it alive and reset it if needed. In the worst case scenario, notifications are delayed 60 seconds.

It seems you are dealing with the battery optimization issue. Did you check https://support.signal.org/hc/en-us/articles/360007318711-Troubleshooting-Notifications?

At first boot, Molly-FOSS requests permission to disable the battery optimizations for the app, with a reminder in the conversation list. Maybe there is an issue and the popup is not displayed. I will check it out.

**Comment by cm157** [comment]
At the risk of sounding like a complete idiot how do I know if I am running Molly or Molly FOSS? On fdroid I see just two options Molly and Molly "Staging". I just downloaded the one named Molly.

**Comment by valldrac** [comment]
The versions are different: v5.0.8-1 vs v5.0.8-1-FOSS. You can check it in multiple places:

- In Molly, go to Settings > Advanced
- In Fdroid, in the version list below the description of the app

Also, in Fdroid configuration, see if the molly's repo URL has "foss' on it.

**Comment by MaxsimLionel** [comment]
I am having issues with this currently. I have battery optimization set to off. I see the app in my android 13 active apps page in quick settings. There is no notification on the chats page of Molly and sometime messages are delayed until I open the app. I have a pixel 6 running the latest Graphene OS. I am using Molly FOSS.
