### ISSUE TITLE
Group calls don't disappear from the chat history

### ISSUE THREAD

**Issue by SrEstegosaurio** [mollyim/mollyim-android#180]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

Group calls do not disappear from the chat history like normal calls do in DM if auto destruction is configured.
This might be compromising in some situations and can lead to risk in some threat models.

### Steps to reproduce

1. Start a group call in Molly.
2. Wait for the configured timer to expire.
3. The group call mnotification would still be there.

### Molly version

v6.17.3-1-FOSS

### Android version

Android 10

### Device

DOOGEE s96 PRO

**Comment by valldrac** [comment]
Thank you for the report. Could you please try to reproduce it using the most recent version v6.18.4-1?

**Comment by SrEstegosaurio** [comment]
I've updated to the last version _(FOSS variant)_ and group calls still not have a timer.

**Comment by valldrac** [comment]
Should be fixed now in v6.19.9-1.

**Comment by SrEstegosaurio** [comment]
Thanks!
