### ISSUE TITLE
Add "Get it on Accrescent" to README

### ISSUE THREAD

**Issue by lazytownfan** [mollyim/mollyim-android#186]
### Is there an existing request for this?

- [X] I have searched the existing issues

### Feature description

I would like to see the "Get it on Accrescent" button added to the README, as described in Accrescent's [documentation](https://accrescent.app/docs/guide/publish/post-approval.html) after approval.

This would help users know with certainty that Molly is officially present on Accrescent.  (I saw some confusion about four months [ago](https://nitter.cz/mollyimapp/status/1615050045803401228#m).)

(I would've made a PR, though it seems that Accrescent only makes the necessary HTML code to approved app uploaders via the Accrescent site dashboard.)

**Comment by valldrac** [comment]
```html
<a href="https://accrescent.app/app/im.molly.app">
    <img alt="Get it on Accrescent" src="https://accrescent.app/badges/get-it-on.png">
</a>
```

**Comment by lazytownfan** [comment]
Thank you!  PR #187 should add the Accrescent button now (after ensuring both Accrescent and F-Droid buttons are the same size).
