### ISSUE TITLE
Which branch or tag should I merge for stable updates?

### ISSUE THREAD

**Issue by TheTanmay1** [mollyim/mollyim-android#189]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

Hello, mollyim-android maintainers and contributors!

I'm interested in updating my fork of the mollyim-android repository and want to make sure I'm merging with the most stable branch or tag. Could you please provide guidance on which branch or tag I should merge with to ensure a stable experience?

Here's what I'm looking for:

The branch or tag name that represents the most recent stable release.
Any specific instructions or recommendations for merging, if applicable.
If there's a recommended method for staying updated on future stable releases, please let me know.
Thank you for your time and for your work on this project. I'm looking forward to contributing and staying up-to-date with mollyim-android's development.

I tried merging from default branch then i was having some bugs, so thatswhy please help me.

### Steps to reproduce

1.
2.

### Molly version

6.18.4

### Android version

12

### Device

samsung

**Comment by valldrac** [comment]
Basically, the main branch is the stable version. So, if you've made some changes you can merge them into the main branch.
