### ISSUE TITLE
Integrate Update Mechanism

### ISSUE THREAD

**Issue by cm157** [mollyim/mollyim-android#19]
I have been using Molly-IM for a few months now this is I think the 3rd in a series of small feature enhancement I would like to suggest to the community / developers. 

In my experience non tech people are not good at keeping these apps up to date. Something so simple as having them open fdroid to perform an update is lost of them. It's not uncommon. 

Is it possible that Molly integrates an update notification or even self update mechanism? Could be as simple as a notification and a link to download the next update to something more substantive like the app will download the update, authenticate it and then present option to install it. 

Just an idea. I have been trying to get more people to adopt Molly in my circle and thus far the idea of downloading an app to download an app and keep it up to date is something that for non tech people seems a bit strange.

**Comment by valldrac** [comment]
I agree. It's a good idea to have a self update mechanism regardless of fdroid.

Signal already has one but it is disabled in Molly. So it is a matter of adapting it for Molly. Self-updates are mandatory in Signal, but I plan to make it optional and opt-in.

Thanks for your suggestions!

**Comment by cm157** [comment]
At the risk of sounding like a complete idiot how do I know if I am running Molly or Molly FOSS? On fdroid I see just two options Molly and Molly "Staging". I just downloaded the one named Molly.

**Comment by valldrac** [comment]
I added the auto-updater in v5.4.12-1. It's optional and disabled by default. You can enable it under the advanced settings. But the updater won't do anything until a new release is available :laughing:

The updater checks the fdroid repo daily. When an update is available, it downloads the APK and shows a notification to tell the user to install it.

For the next release I want to include an announcement inside the app (with a so called "megaphone") to suggest the user to turn the auto-updater on.
