### ISSUE TITLE
Tapping photo gets the error:"Media no longer available"

### ISSUE THREAD

**Issue by nospace-here** [mollyim/mollyim-android#190]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

After updating Molly, I can't view any of my sent images in fullscreen anymore, despite being normally visible in chat.

![IMG_20230514_121658_823](https://github.com/mollyim/mollyim-android/assets/77444261/1a547cb4-2c96-438e-91a1-c1d2d1a4a272)

### Steps to reproduce

1. Update Molly (not FOSS) via F-Droid
2. Tap on any own image sent before the update
3. Error message appears 

### Molly version

V6.19.9-1

### Android version

Android 13

### Device

Pixel 4a

### Link to debug log

https://debuglogs.org/android/6.19.9/013d33c6a4f9ab73a985339061a6e1714f92edfbf2462bf19992710b600fca00

**Comment by BHydden** [comment]
Same error occurs with FOSS version sourced from Accrescent.
Pixel 6

**Comment by BHydden** [comment]
Confirmed fixed 👍 thanks
