### ISSUE TITLE
Navigation bar

### ISSUE THREAD

**Issue by Grkrz** [mollyim/mollyim-android#192]
### Is there an existing request for this?

- [X] I have searched the existing issues

### Feature description

Is it possible to make to option to disable the navigation bar? This funcfion is useless in my opinion.

**Comment by Jatinverma0786** [comment]
I didn't get what you are asking for? Can you Explain in Brief it

**Comment by BHydden** [comment]
At a guess I think this *might* be asking to remove the Chats / Calls buttons down the bottom. I agree it's not very clear as currently stated.

**Comment by Grkrz** [comment]
Apology for not being clear at the very beginning. 
I meant what BHydden mentioned above.
The call, chat (stories) navigation bar.

**Comment by valldrac** [comment]
This feature has been implemented since version v7.1.2-1. You can disable the navigation bar in the appearance settings.
