### ISSUE TITLE
Voice message audio quality terrible with Xiaomi 13 Ultra

### ISSUE THREAD

**Issue by Kurasami** [mollyim/mollyim-android#195]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

When sending a voice message via Molly on my Xiaomi 13 Ultra the quality is extremely bad. It sounds noticeably distorted, wobbly and in general low quality and there is even some degree of echo in silent areas.

If I use a third-party recording app, or even another software like Whatsapp or Telegram. The voice quality is absolutely crystal clear and is indistinguishable between other apps. Only Molly sends my voice in such low quality.

I have the setting set to "High" for sent media in Molly's settings.

Here are some test audio clips:

1. Molly (terrible) - https://voca.ro/11UOhe93I5m4
2. Recorder (excellent) - https://voca.ro/1oIgTD8xuK3R
3. Whatsapp (excellent) - https://voca.ro/1j0XwlQGJhGq

Whilst I do understand it is possible to hear me well enough 

### Steps to reproduce

1. Send a voice message on Molly > Sound quality is terrible
2. Send it on practically any other app (Whatsapp, Telegram, recorder app) and it is crystal clear

### Molly version

6.20.5-1-FOSS

### Android version

13

### Device

Xiaomi 13 Ultra

**Comment by valldrac** [comment]
It's possible that this issue has already been resolved by Signal. I can't test it because I don't have that device model. Please, if the issue persists, reopen the ticket.
