### ISSUE TITLE
Molly locks when voice call ends

### ISSUE THREAD

**Issue by lazytownfan** [mollyim/mollyim-android#198]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

Molly will lock itself whenever a voice call ends.

(I've been calling more people on Signal who are more comfortable with calling vs. texting recently.)

I think this could technically a crash, because the first time I noticed this, I saw the Android system prompt/box showing that Molly had stopped/crashed, before Molly went back to the local database lockscreen.

### Steps to reproduce

1.  Start a voice call.
    * It doesn't matter if you or the caller start the call
2.  The voice call ends.
    * I think so far I've observed this when the other person ends the call, but I don't know if also happens if you end the call
3.  If you're lucky, then you might see a "Molly keeps stopping" Android message; otherwise, Molly immediately locks itself and asks you to enter the database password again.

(Unfortunately, I wasn't able to make the debug log right after this happened, but several hours later.  It happened both today and yesterday.)

### Molly version

v6.23.5-1-FOSS

### Android version

Android 13

### Device

Google Pixel 4a

### Link to debug log

https://debuglogs.org/android/6.23.5/f2b6bb16bd450fecb513bfd9a9d660c33f17037ebd1a6c54afdf85b969aefd7a

**Comment by valldrac** [comment]
Fixed by Signal in commit https://github.com/signalapp/Signal-Android/commit/dd40517f1200c2fcf0751715315f172e35b59114

**Comment by lazytownfan** [comment]
Thank you!  Somehow the fact that this is resolved upstream is comforting.

I'll keep this issue open until Molly updates to or passes version 6.24.4, in the case anyone experiences this issue & starts to investigate it from the angle of Molly.

**Comment by valldrac** [comment]
Even though most crashes should be fixed in v6.24.4-1, it seems like there are still a few corner cases that need to be resolved, probably in v6.25.x

**Comment by lazytownfan** [comment]
Alright, I'll wait until v 6.25+ before closing out this issue.
