### ISSUE TITLE
MASSIVE battery drain while idling!

### ISSUE THREAD

**Issue by codeonblocks** [mollyim/mollyim-android#199]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

Molly-FOSS is taking up a HUGE amount of my battery life and it caused my phone to die when I really needed it. I'm not sure what's causing this huge amount of drainage.
![Screenshot_20230624-214048](https://github.com/mollyim/mollyim-android/assets/32179921/9fef165b-39d5-4d8e-bd7b-036fbbe198ae)

### Steps to reproduce

1. Install GrapheneKS without GApps or GPlay Services.
2. Install Molly-FOSS through Github releases 
3. Turn off battery optimization

### Molly version

v6.23.5.1-FOSS

### Android version

Android 13

### Device

Google Pixel 6

### Link to debug log

https://debuglogs.org/android/6.23.5/7947a1ba1f484910e77660b3f646d14b73cb7935784b6d17b08bce96b7692b26

**Comment by valldrac** [comment]
It's a known issue that Molly-FOSS (and Signal without Play Services) tends to use up more battery compared to Molly with FCM push notifications. The amount of extra battery drain mostly depends on how good or bad your Internet connection is.

I noticed many connection drops and errors in your log along the day, which means Molly has to rebuild the connection to the server every minute or so, consuming a lot of battery.

We are already tracking this issue in #126.

**Comment by codeonblocks** [comment]
> It's a known issue that Molly-FOSS (and Signal without Play Services) tends to use up more battery compared to Molly with FCM push notifications. The amount of extra battery drain mostly depends on how good or bad your Internet connection is.
> 
> I noticed many connection drops and errors in your log along the day, which means Molly has to rebuild the connection to the server every minute or so, consuming a lot of battery.
> 
> We are already tracking this issue in #126.

Thanks for letting me know. I use a VPN that has a rotating IP (I get a new IP address every few mins). Is that what's causing the network to keep dropping?

**Comment by codeonblocks** [comment]
I also use the Orbot Proxy, is that also causing the networking issue?

**Comment by codeonblocks** [comment]
I found that the issue with the constant connection drops was due to my VPN (SurfShark). I went into the settings to disable the VPN for Molly only, and I stopped seeing the connection drop logs. There seems to be an issue where Molly is not cooperating properly with VPNs. @valldrac

**Comment by BHydden** [comment]
Molly-FOSS works perfectly well for me with always on proton vpn
