### ISSUE TITLE
[v5.0.8.1-FOSS] App does not show conversations after update

### ISSUE THREAD

**Issue by ph00lt0** [mollyim/mollyim-android#20]
After the last update conversations disappear after a day of installation. Also all contacts are non-visible so it's impossible to start a new conversation and the profile picture in the left corner on the home screen also does not function anymore. It seems to me that the elements are somehow hidden. The issue appears in both dark and white theme
I reinstalled the application and after a day the exact same bug occurred. 

Is there any information I could provide that might help?

![Screenshot_20201221-121732](https://user-images.githubusercontent.com/15004290/102772250-75be8c00-4387-11eb-954a-1740e92bc1be.jpg)

**Comment by valldrac** [comment]
Thanks for reporting it. I received yesterday another bug report very similar from your description, and we determined it is a bug in Signal not Molly.

https://github.com/signalapp/Signal-Android/issues/10284

Please confirm if it may be your problem or not. Also try as a workaround to kill the app instead of re-installing it.

**Comment by ph00lt0** [comment]
Thanks for prompt reply @valldrac 
>  I reinstalled the application and after a day the exact same bug occurred.

Problem did not appear in Signal for me, although it might indeed be related.  Re-installation fixes it just temporary but the bug returns after a day of usage. Just figured out a reboot fixes the issue. I'll close the issue for now and await the Signal bugfix and see if that helps.

**Comment by valldrac** [comment]
Let's keep this ticket open to track the fix.

**Comment by ph00lt0** [comment]
@valldrac thanks :)
