### ISSUE TITLE
Document FAQ: Is the userbase the same as Signal?

### ISSUE THREAD

**Issue by maltfield** [mollyim/mollyim-android#201]
### Is there an existing request for this?

- [X] I have searched the existing issues

### Feature description

This ticket is a request to add a FAQ section to the website, at least including an answer to the question:

 * If I get Molly, can I communicate with users who run Signal?

The first, most obvious question that users will have when the hear that there is a "signal fork" is -- how forked is it? Does it use Signal servers? Is the userbase distinct? Can Molly users communicate with Signal users? Can Signal users communicate with Molly users?

This question (and others) should be made *very* clear to users in the FAQ section of the website.

**Comment by maltfield** [comment]
As an aside, though this isn't documented anywhere, searching around the github issues shows that Molly users Signal Servers.

As such, it really shouldn't be called a fork. It should be called an alternative frontend.

**Comment by valldrac** [comment]
Thanks for the request. We're gonna swap out the website for a brand new one, and the new website will have a proper FAQ section.

In the meantime, this question is addressed in the README's introduction:

https://github.com/mollyim/mollyim-android#introduction.

Our project aims to have its own servers, so I think the term "fork" is the most accurate.

**Comment by valldrac** [comment]
> When that happens, will that mean that Molly users will no longer be able to communicate with Signal users?

We've talked about this a lot in our Matrix chat room. Molly will still connect to Signal, so you can continue chatting with your Signal contacts without any issues.
