### ISSUE TITLE
Molly does not delete messages on linked devices when 'deleting for everyone'

### ISSUE THREAD

**Issue by mce0** [mollyim/mollyim-android#207]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

If you send an message to yourself and delete it 'for everyone' the message is only deleted on Molly and not e.g. Signal Desktop.

### Steps to reproduce

1. Send a message in the 'Note to Self' chat
2. Delete the message within Molly 'for everyone'
3. The message is deleted in Molly but not in e.g. Signal Desktop

### Molly version

v6.25.5-1-FOSS

### Android version

Andoird 13

### Device

Google Pixel 6

**Comment by valldrac** [comment]
I can't reproduce this bug with the latest code and Molly linked as a secondary device (#157). When I delete messages, they disappear from both apps.

It seems like Signal Desktop might be sticking to a 3-hour time limit for message deletion, which means you can only delete messages sent in the last 3 hours. But Molly doesn't enforce this limit for notes-to-self chats.
