### ISSUE TITLE
Sent messages don't appear on linked device

### ISSUE THREAD

**Issue by njmdietrich** [mollyim/mollyim-android#211]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

If I link molly to another device using the newly added linked device functionality, I can send and receive messages just fine. However, messages sent from my main device do not show up on the linked device. This was not an issue on the latest insider release for this feature.

### Steps to reproduce

1. Link molly to an existing device
2. Send messages from the main device

### Molly version

v6.31.2-1-FOSS

### Android version

Android 13

### Device

Samsung Galaxy Tab S5e

### Link to debug log

https://debuglogs.org/android/6.31.2/b1359ce8ae7ef5961ab0ba4f88681f4a1b792a8bd5917a8552002f048a608b26

**Comment by valldrac** [comment]
Thanks for the bug report. Please confirm whether force-stopping both apps does not resolve the issue.

**Comment by njmdietrich** [comment]
So I had only tried force stopping the linked Molly so far, turns out force stopping both fixes it! Thx for the help

**Comment by valldrac** [comment]
Got it! Restarting the app is a workaround, but there's definitely a bug somewhere. I'll keep the issue open until I track it down and fix it.

**Comment by Simsala91** [comment]
As an info: This happens to me on Signal-Desktop <-> Signal-Android too. Sometimes, it takes a long time for the messages I sent from Signal-Desktop to appear on Signal-Android. Might not be Molly related.

**Comment by kastnerp** [comment]
Same problem here. Force stopping on both devices does not help.

**Comment by valldrac** [comment]
We’ve released several new versions since this issue was reported, and we believe this problem has been resolved. If you’re still experiencing it, please open a new ticket with the latest version details. Thanks!
