### ISSUE TITLE
while building i am getting this error please help

### ISSUE THREAD

**Issue by TheTanmay1** [mollyim/mollyim-android#212]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

A problem was found with the configuration of task ':libsignal-service:sourcesJar' (type 'Jar').
  - Gradle detected a problem with the following location: 'D:\02)android_studio_files\11)molly_16sep_g4\libsignal\service\build\generated\source\wire'.

### Steps to reproduce

1.
2.

### Molly version

v6.31.2-1

**Comment by valldrac** [comment]
I believe the commit 50a6fb31b5efe2de78ce290e6a8dcf5ccc0a42d9 fixed this issue.
