### ISSUE TITLE
Set Disappearing message timer : message 

### ISSUE THREAD

**Issue by luckyinspect** [mollyim/mollyim-android#213]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

Disappering messages are erased correctly.

On the other hand when a person setup the time.
This message does not disappear

Ex : 
XXX set the disappearing message timer to 30 seconds

which de facto prevents the conversation from being automatically deleted.

### Steps to reproduce

1. Set time
2. Write message

The message will disappear.
The message of time will not disappear.

### Molly version

v6.31.2-1

### Android version

android 13

### Device

pixel 

![signal-2023-09-19-211423](https://github.com/mollyim/mollyim-android/assets/145504258/80696b8f-3fd2-4297-a9a9-f777168ca8cc)

**Comment by valldrac** [comment]
The timer setup messages don't disappear. That's on purpose, to avoid any confusion or potential tricks by the recipient. But you can delete them manually by selecting them and hitting delete in the menu.
