### ISSUE TITLE
Fdroid: Improve description by adding parts from README

### ISSUE THREAD

**Issue by siddhpant** [mollyim/mollyim-android#214]
### Is there an existing request for this?

- [X] I have searched the existing issues

### Feature description

Currently the description on Fdroid doesn't tell much about Molly.

Much of the README starting from the features section can be added.

Please improve the description by adding at least the features section. That should at least convey why to get Molly.

**Comment by valldrac** [comment]
You're totally right. I just updated it. Thanks for letting us know!
