### ISSUE TITLE
Publish on official F-Droid.org

### ISSUE THREAD

**Issue by rugk** [mollyim/mollyim-android#215]
### Is there an existing request for this?

- [X] I have searched the existing issues

### Feature description

It would be great to see this Android app on F-Droid!

[F-Droid](https://f-droid.org/) is an Android app store specifically for free/libre open-source apps. It would be great if your app could be released there, as it is the number one for getting FLOSS Android apps for many people.
F-Droid also builds all apps from source ([optionally even reproducible](https://f-droid.org/en/docs/Reproducible_Builds/)), so downloads from there can be trusted.

The [app developer FAQ](https://f-droid.org/en/docs/FAQ_-_App_Developers/) or [the quick start guide](https://f-droid.org/en/docs/Submitting_to_F-Droid_Quick_Start_Guide/) may help you to get started.

BTW a release on F-Droid could also bring some (more) popularity (in case that is intended), as it will show up in the app (new apps are featured there).

---

Note I **did saw the [current download option](https://molly.im/download/fdroid/)**. However, that is adding some custom repo from molly.im, which means:
* it is not built by F-Droid(.org) so technically the download badge on your home page is kinda misleading, as it is not built by them
* I have no guarantee by F-Droid that the app is really FLOSS.
* _You_ do not have the publicity by having it in the official repo. (as indicated above)
* I have a harder way of downloading and using it, as I cannot just search for the app on F-Droid.
* _You_ have to maintain the F-Droid repo for updates etc.

Don't get me wrong, there is nothing wrong with having it in your own repo, I would just like to (at least) _also_ see it on f-droid.org.

**Comment by ETH1166** [comment]
I completely agree to this and had considered to ask for the same. Make Molly more popular!

I am a new Molly user, mainly due to the fact, that Signal is not allowing Android tablets to be coupled to the main Android phone as a secondary device. If Molly would have been on the official F-Droid repository l would have tried it months earlier...

**Comment by valldrac** [comment]
I agreed in #16, but as far as I know, the folks at F-Droid have always been against adding Signal or any fork like Molly to the official repository. Just check out their comments of the request for packaging: https://gitlab.com/fdroid/rfp/-/issues/2297

I've tried reaching out to them to sort it out, but no response yet. If there's any interest from F-Droid in adding Molly, please let me know.

Also, Molly has always support reproducible builds. See the instructions at this link: https://github.com/mollyim/mollyim-android/tree/main/reproducible-build

**Comment by rugk** [comment]
Your reproducible build link does not work, you likely meant https://github.com/mollyim/mollyim-android/tree/main/reproducible-builds

Anyway, [asked for clarification in the F-Droid MR](https://gitlab.com/fdroid/rfp/-/issues/2297#note_1577234232).

**Comment by licaon-kter** [comment]
> the folks at F-Droid have always been against adding Signal or any fork like Molly to the official repository.
> https://gitlab.com/fdroid/rfp/-/issues/2297

So you've read ALL that and the conclusion was _"F-Droid is against"_ and no _"Signal network owner is against F-Droid"_ ? U joking right?

**Comment by marek22k** [comment]
> folks at F-Droid

I think this is just one person.

**Comment by marek22k** [comment]
Maybe it would also be a solution to publish Molly in IzzyOnDroid? I think that is a repo that also many F-Droid users have.

**Comment by rugk** [comment]
/cc @IzzySoft

AFAIK you also have influence how to process for app inclusion works at F-Droid and maybe [whether only one person decides on the inclusion in apps on F-Droid](https://gitlab.com/fdroid/rfp/-/issues/2297#note_1578925129) or how that works in general, as you have some insight there AFAIK.

**Comment by IzzySoft** [comment]
All details have already been mentioned there. F-Droid won't risk a fight with the Signal team which clearly stated they won't allow any 3rd-party apps access to their servers. There were already issues in the past with this problem. Add Moxie's dislike for F-Droid to it, and you get the picture, @rugk. Sorry, but the F-Droid team cannot waste power for such a fight even if it would go that path – too few hands.

**Comment by rugk** [comment]
Okay understandable, though sad. What about your personal F-Droid repository though?

**Comment by IzzySoft** [comment]
Already answered there: APK size exceeds the limit by more than factor 2. And even less "human power" (only me).
