### ISSUE TITLE
Improve GitHub about part as it looks oudated/mentions only one single feature

### ISSUE THREAD

**Issue by rugk** [mollyim/mollyim-android#216]
### Is there an existing request for this?

- [X] I have searched the existing issues

## This is how it looks on GitHub

![grafik](https://github.com/mollyim/mollyim-android/assets/11966684/1532654e-ef9a-4b43-808e-303dfb5c187a)

Aka:
> A fork of Signal for Android with passphrase lock 

## Problem

IMHO, this does not really say much.

It looks quite outdated, as maybe this was the first feature you've added? But I guess it should not be the thing you mention there as your (only) USP to say like that… :wink: After all, you have a lot more features.

**Comment by valldrac** [comment]
> It looks quite outdated, as maybe this was the first feature you've added? 

You guessed right. Never changed the description since the first release :sweat_smile: Time to update it!
