### ISSUE TITLE
How to change the database locking passphrase?

### ISSUE THREAD

**Issue by dennisroczek** [mollyim/mollyim-android#218]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

I have added a screenlocking passphrase, but sadly have a typo in it. How to change the phrase.

Also turning it off completely doesn't work as Samsung kills apps in background to aggressively and thus having to type it nearly every time. :-(

### Molly version

v6.31.2-2-FOSS

### Android version

11

### Device

Samsung Galaxy A10

**Comment by valldrac** [comment]
In the app's settings menu, under the privacy section, you can choose to turn it off. You can also increase the lock timeout (that starts when the phone screen is locked) which is immediate by default

**Comment by dennisroczek** [comment]
![signal-2023-10-13-192908](https://github.com/mollyim/mollyim-android/assets/3443013/cb200313-6d0c-40c8-90ba-5c5014cd9a6c)
Well, I get regular asked for my passphrase. So, how to deactivate?
