### ISSUE TITLE
Linked devices fail to register for FCM-based notifications

### ISSUE THREAD

**Issue by chenxiaolong** [mollyim/mollyim-android#226]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

When using Molly as a linked device, FCM-based notifications don't seem to work despite Google Play Services being available. However, if it's set up as the primary device (same Molly version and build), then FCM-based notifications work.

### Steps to reproduce

1. Set up a primary device using either using Signal or Molly.
2. Set up a linked device using Molly.
3. Molly on the linked device immediately shows a an `Optimize for missing Play Services` message: [Screenshot_20231013-001131](https://github.com/mollyim/mollyim-android/assets/646253/22bc5bb8-3672-4a2b-8786-d9fc33f48bab)

Force killing the app and starting it again doesn't seem to make a difference. The message disappears, but `org.thoughtcrime.securesms.messages.IncomingMessageObserver$ForegroundService` ultimately ends up running and seems to use the websocket method instead of FCM.

### Molly version

v6.35.3-1

### Android version

Android 14 and Android 13

### Device

Google Pixel 7 Pro and Samsung Galaxy Tab S8 Ultra

### Link to debug log

https://debuglogs.org/android/6.35.3/c8e739a1db336833b0977cf749592c0977e8de5111810dbd04135bc54229a7de

**Comment by valldrac** [comment]
Thanks for the detailed report. Unfortunately, the Signal server does not currently support FCM-based notifications on linked devices. It's limited to the primary device.

**Comment by chenxiaolong** [comment]
Ah, I wasn't aware of that. Thanks for the explanation!

**Comment by nisc** [comment]
Just to confirm, is this still the status quo?
