### ISSUE TITLE
Incorrect emojis in the app reaction and emoji picker

### ISSUE THREAD

**Issue by tfardet** [mollyim/mollyim-android#237]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

Some emojis do not seem to be correctly implemented in Molly.
I just switched and this issue was not present in Signal.

Here are screen captures in Molly, my desktop client, and my correspondent Signal app.

![molly view (emoji I selected)](https://github.com/mollyim/mollyim-android/assets/79037344/9083f557-2dc3-4baa-9944-c1377ac1a0f5)
![correspondent signal view (not the emoji I thought I selected)](https://github.com/mollyim/mollyim-android/assets/79037344/ae0f4075-d410-4f71-a607-0a44d3327db9)
![desktop view (not the emoji I thought I selected)](https://github.com/mollyim/mollyim-android/assets/79037344/feeeddbf-ab82-47ea-b6f2-4d9ee136309e)

### Steps to reproduce

1. searched for :ok_hand: (not present in yellow, so select the light skin tone)
2. on signal desktop, see the actual emoji sent (leftwards_pushing_hand) in the default yellow color

### Molly version

v6.35.3-1-FOSS

### Android version

Android 12

**Comment by valldrac** [comment]
Closing this ticket because we couldn't replicate the bug.
