### ISSUE TITLE
question : ability to register as "linked device"

### ISSUE THREAD

**Issue by squalou** [mollyim/mollyim-android#24]
Hi,

just wondering if it would be technically possible to install molly on a secondary android device, and register it as a linked device.

(like one would do with signal desktop client)

Could be useful.

thank you !

**Comment by fat-tire** [comment]
This is the number one failing of the Android app IMO.  Would require a patch like [this](https://github.com/Trolldemorted/Signal-Android/commit/512a12474b4fa3fdfd18bf60358b2729ab8f000c) that is kept up to date and in sync with mainline Signal.  I have NO idea why they haven't done this already.

#2 "feature" being a ChromeOS release, which as of at least a few months ago required zero changes.

**Comment by valldrac** [comment]
It is possible. But I'm sorry this feature would be an endless source of headaches, given the speed of development of Signal right now, and the number of hidden bugs in the sync internals and UI that it would uncover. I guess some of those bugs would affect the desktop and upstream app too, impossible to address only by me.

Not feasible for now.
