### ISSUE TITLE
Backup not working

### ISSUE THREAD

**Issue by GFNIAE** [mollyim/mollyim-android#243]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

I have installed mollym-android ( last released from github). I restored a backup made with (updated) signal app and it worked.
I can use mollym with no issues.
However molly ist not able to save a new backup. When I try to do so by enabling backups, the backup process seems to start and displays increasing percentage. When it reaches near 99%, an error notification "backup failed - tap to manage backups" pops up. In molly paramaters the "last backup" field says : "never"

I tried again signal app : reinstall, restore the same backup, and enable new backups : is does work as expected

I tried again and again with molly app, and I always end up with the same error.

Molly has the same permissions than signal app and specifically write permissions.

So it seems something is broken in molly backup process. I add debug log. Could you have a look and see whether it’s an issue with molly or some specific config on my smartphone ?

### Molly version

v6.40.4-1-FOSS

### Android version

Android 11

### Device

Samsung A20

### Link to debug log

https://debuglogs.org/android/6.40.4/724e28503e5c3ea16282a33640c94d708bc3325a4e45a77ebad93fcb28773275

**Comment by xenithorb** [comment]
I can confirm this behavior. There also seem to be some other molly bugs related to backups recently, what's up with that?

**Comment by valldrac** [comment]
There's a problem we know about with corrupted attachments. I noticed in your log that the app crashed a few days before the backup restore problems, because your device disk was full. That might be why some attachments are recorded with the wrong size.

Please track the resolution progress for this issue in ticket #139.
