### ISSUE TITLE
Let user to decide whether 'Screen security' option is enabled while enabled 'Screen lock'

### ISSUE THREAD

**Issue by mjdNjhNJ** [mollyim/mollyim-android#250]
### Is there an existing request for this?

- [X] I have searched the existing issues

### Feature description

**Current Behavior**

Option 'Screen security' is enabled and cannot be disabled after enabling 'Screen lock' option in 'Privacy'.

**Proposed Behavior**

'Screen secruity' option is independent of 'Screen lock' state.

**Comment by valldrac** [comment]
We force "screen security" to stop the app screen from appearing in the app switcher on your device, so your chats or messages won't accidentally get seen by someone who is not authenticated by Molly's screen lock.

**Comment by mjdNjhNJ** [comment]
@valldrac That is understandable. What are the arguments against not letting users decide for themselves? This could be enabled by default and banner informing about possible risks can popup first before actually disabling such feature.
