### ISSUE TITLE
Linking Molly as a second device is not possible; causing errors

### ISSUE THREAD

**Issue by Uneccessary** [mollyim/mollyim-android#254]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

![image](https://github.com/mollyim/mollyim-android/assets/145043411/5b111540-76ca-45e2-a0da-935827cba879)

### Steps to reproduce

1. Open Signal / Molly on your primary device and go to the linked devices section
2. Open Molly on a second device and try to link it
3. You will experience always a error

### Molly version

Molly v6.40.4-1

### Android version

Android 14

### Device

Samsung

**Comment by pvi-github** [comment]
I have the same problem with Signal 5.40.5 on the mobile and Molly 5.40.4-1 on the tablet.

Details : Either I have "Network error" on the  mobile side or "Devide was approved" on the mobile but in all cases, I have a message "the delay for the main device has expired, blah bla prepare and try again" on Molly side, and this no matter how quick I can be to flash the code or what camera (front or back) i use.

I also tried the pre-release 5.41 of Molly with the very same behavior.
