### ISSUE TITLE
Android Auto - FOSS version doesn't show in AA launcher

### ISSUE THREAD

**Issue by kaibagley** [mollyim/mollyim-android#263]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

I am unable to use the MollyFOSS version of the app in Android Auto, while the non-FOSS version shows up fine, even though i have developer settings > unknown sources in AA enabled.

### Steps to reproduce

1. AA Developer Settings > Enable "Unknown Sources"
2. Download MollyFOSS
3. Check AA launcher, doesn't show up
4. Download Molly
5. Check AA launcher, shows up

### Molly version

v6.41.3-2

### Android version

Android 14 (GrapheneOS)

### Device

Pixel 7 Pro

**Comment by BHydden** [comment]
Why are you using Molly FOSS if you gave g services installed?  Since AA req g services there's probably a good chance it needs the version of Molly that includes g blobs

**Comment by kaibagley** [comment]
I'm actually using the Unified Push fork of Molly, and I believe that is forked from the MollyFOSS from this repo

I'm also having the same issue getting Organic Maps to work on AA, but am successful getting Tempo, Element, AntennaPod working. But that makes sense, all these apps might include the google blobs you're mentioning.

Does MollyFOSS actually have support for AA?

**Comment by valldrac** [comment]
> Does MollyFOSS actually have support for AA?

It might be possible, just a matter of declaring AA support in the manifest. I'll give it a try and let you know.

But, keep in mind, it could also need adding GMS library to the app, making it incompatible with FOSS.

**Comment by kaibagley** [comment]
Thanks so much for the effort. If it ends up being something incompatible with the FOSS version I'll move back to the issue on the UnifiedPush fork.

**Comment by kaibagley** [comment]
I can confirm this is fixed for me. Thanks guys, absolute legends once again
