### ISSUE TITLE
Device unregistered

### ISSUE THREAD

**Issue by abh-oss01** [mollyim/mollyim-android#27]
I just logged in to my account in the signal apo from the website, and Molly now says "Device is not registered" and I have to re register.
I thought Molly and Signal can exist on the same device side by side?

![20210118_111418.jpg](https://user-images.githubusercontent.com/56572179/104876877-90802280-597e-11eb-9744-280d934ca215.jpg)

**Comment by planetprivate** [comment]
No. Only one...

https://github.com/mollyim/mollyim-android#compatibility-with-signal

> > 
> However, you cannot use the same phone number on both apps at the same time. Only the last app to register will remain active, and the other will go offline.

**Comment by occ2018** [comment]
also note signal servers also do NOT allow this. So impossible.

**Comment by abh-oss01** [comment]
![20210119_073230.jpg](https://user-images.githubusercontent.com/56572179/104978717-861a6300-5a28-11eb-88f8-a1e697ad37cf.jpg)


Looks like I misread...
but anyway, I thought (more like assumed) signal is cross platform(?)
Guess I was wrong.

**Comment by planetprivate** [comment]
> signal is cross platform(?)

means IIRC, it is available for different OS.

**Comment by valldrac** [comment]
Thanks for helping me with the user support :heart:
