### ISSUE TITLE
Background connection

### ISSUE THREAD

**Issue by abh-oss01** [mollyim/mollyim-android#28]
"Molly Background connection enabled" 
This is a persistent notification, what is this and how do I disable continuous b/g connection and sync? I'm concerned about battery being depleted really fast.
![20210118_111844.jpg](https://user-images.githubusercontent.com/56572179/104877041-f2408c80-597e-11eb-875c-378229eba68a.jpg)

**Comment by planetprivate** [comment]
Do you mean it is OK for you if the messages are not delivered?

if you need instant notification then it needs to drain battery...

You can press and hold on the notification or go to Android->Settings->Apps-> select Molly and remove notification.

**Comment by abh-oss01** [comment]
No, I mean isn't there a legit way to not let it run in the bg forever? Even after closing (not force closing) the app, it continues to run... then I have to force close it from app settings (which I somehow do not want to so because it might not retrieve messages, right?)

So I just was asking that why doesn't molly close automatically once exited using the "Back" button?

**Comment by planetprivate** [comment]
> which I somehow do not want to so because it might not retrieve messages, right?

If you want messages to be retrieved then it needs to run in the background.

>  I mean isn't there a legit way to not let it run in the bg forever?

So you want it to stop running. (i.e) You will not get messages. 

**Please tell what you want?**

**Comment by valldrac** [comment]
As @planetprivate correctly said, that background service allows you to receive new message notification, when Google Play Services are not available.

Although you always see the notification on top, the service remains sleep most of the time. It just wakes up to keep  the connection to the server active. It isn't a big thing. Same technology as standard push notifications.

**Comment by abh-oss01** [comment]
> Although you always see the notification on top, the service remains sleep most of the time. It just wakes up to keep  the connection to the server active. It isn't a big thing. Same technology as standard push notifications.

It doesn't eat up battery as much as I think it does?

**Comment by valldrac** [comment]
> It doesn't eat up battery as much as I think it does?

Hard to tell you ;-) Similar to use the app to chat five minutes more per day? I don't know.

There is an improvement pending to reduce the consumption up to 50% of the actual background service consumption, which is already low.
