### ISSUE TITLE
Molly as linked device is sending content-less messages in my conversations

### ISSUE THREAD

**Issue by brendanny** [mollyim/mollyim-android#289]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

I have Molly as a secondary device on my Pixel tablet and after about a week, I opened Molly again on it. As part of the syncing and receiving cached messages the following happened:

1) Content-less messages appeared in my conversations in Signal on my primary device and in Molly, but not in my linked Signal Desktop
2) I assume because of these content-less messages being sent, a pending message request was accepted
3) My primary device Signal received notifications for every single message reaction that I'd received since the last time Molly synced.

### Steps to reproduce

1. Link Molly as a secondary device
2. start sending messages and using Molly/Signal

### Molly version

v7.0.1

### Android version

Android 14

### Device

Google Pixel Tablet

### Link to debug log

https://debuglogs.org/android/7.0.1/f34f238bd2a4dd4fa59a95d205acb3bfa92579de94c809350def7b34815ce9ca

**Comment by valldrac** [comment]
This should be resolved in the latest versions. Let us know if it still happens.

**Comment by tennisballer** [comment]
Hi @valldrac,

I'm experiencing the same "content‑less messages" bug described in this issue on the latest Molly-FOSS version [insert your version number, e.g., v8.7.3-2. I'm using GrapheneOS on a Pixel 8 Pro (primary) and two to three linked Android devices (a Pixel 10 XL and another phone/tablet), all kept online simultaneously.

The phantom messages are empty "Media message" notifications from my own number (Note to Self). They appear primarily on the linked devices, but occasionally on the primary when it comes online after being offline. Tapping them opens an empty conversation, and the ghost actually inserts itself as a real message and immediately marks itself as read—corrupting the unread state of the chat.

**What I've tested:**
- Clean installs of Molly-FOSS, with no restored backups
- Both WebSocket and UnifiedPush notification methods (ghost occurs with both)
- Reduced to only one linked device for a period—ghost still appeared, but seems more frequent with 2–3 linked devices
- Database cleanup, disabling battery optimization, force‑stopping, reboots
- Confirmed that linking a desktop (Signal Desktop) does **not** trigger the ghost—only Android linked devices do
- No VPN, firewall, or custom DNS active during testing
- I'm currently running all linked devices online simultaneously (2–3 devices), which may be exacerbating the sync chatter

**What I haven't been able to do yet:**
- I enabled Android's Notification History and am waiting to catch the ghost to identify its exact notification channel (no "Media messages" channel appears by default, so I want to see where it's routed). I'll update here once I have that.
- I attempted to submit a debug log via Settings → Advanced → Submit debug log, but the upload is failing (spinner never completes—likely a network issue on my end). I'll attach one as soon as I can get it to work.

This is clearly a regression of #289. The fact that multiple linked Android devices seem to trigger it more often, while a desktop does not, suggests it's something in the Android‑specific linked‑device sync path. Please let me know if I can provide any further details or test builds—I'm happy to help track this down.
