### ISSUE TITLE
Unable to send messages

### ISSUE THREAD

**Issue by abh-oss01** [mollyim/mollyim-android#29]
I just updated to v5.2.3-1-FOSS Production, from `releases` page, installed the apk over the previous (v5.0.8-2-FOSS Production), and now I cannot send messages to anyone, it just keeps spinning.

![20210122_191851.jpg](https://user-images.githubusercontent.com/56572179/105499078-f6eea300-5ce6-11eb-9152-f982eb3df64b.jpg)

**Comment by abh-oss01** [comment]
No proxy or vpn enabled, and still didn't work after force closing, and retrying.
Should I revert back to the previous version which worked?

**Comment by valldrac** [comment]
Sorry, I don't know where the issue may be. It could also be a bug in Signal.

Would you share the debug log so can I take a look? If so, send the URL of the logs to support@molly.im. The tutorial to do it is [here](https://support.signal.org/hc/en-us/articles/360007318591-Debug-Logs-and-Crash-Reports). 

The only solution I can tell you now is do a backup, and reinstall the app. Remember to restore the same or newer version. Rollback to previous versions is not supported.

Whatever you do, please report back here.

**Comment by abh-oss01** [comment]
I just uninstalled Molly and installed it again, and restored the backup, but it **still** isn't working, nothing is being received or sent...
My connection is just fine, any other thing on my phone works as intended, except molly.

Please help me get it back to working normally again soon.

**Comment by valldrac** [comment]
> and it just started working!

Great.

> Does it mean I have to update Molly by uninstalling and installing the new release everytime there's an update?

No. Many people updated like you without any issue. You probably hit a rare bug in Signal.

**Comment by abh-oss01** [comment]
Hey, this bug appeared again, in this latest release. This time I have updated using F-Droid.
I **can't send/receive any messages**, guess I will have to uninstall and reinstall Molly once again to get it working, just like last time.

Please look into this seriously, I think it's not an upstream issue.

Molly version - `v5.0.3-121-FOSS`
Installed (Updated) from F-Droid Molly official repo.
Android version - 10

**Comment by valldrac** [comment]
I'm sorry to hear that. I'd need your debuglog, as I commented before:

> Would you share the debug log so can I take a look? If so, send the URL of the logs to support@molly.im. The tutorial to do it is [here](https://support.signal.org/hc/en-us/articles/360007318591-Debug-Logs-and-Crash-Reports).

If you have already re-installed the app then it's too late. Next time you get the same issue, please send me the debuglog.

There is something on my test devices preventing me from uploading debuglogs. I don't know why yet. You probably won't be able to share them either. I have to dig into this.

**Comment by abh-oss01** [comment]
It happens only on updating the app, without clean installing it...

And yeah I reinstalled it already, works now.
What good a debug log do though? It literally does not connect to the server, that's it, after updating that is.

**Comment by valldrac** [comment]
I can't figure out what could be wrong. It never happens to me. I do many tests before each release, that involves updating the app too.

If I can't reproduce the issue, the only way to know what's really going on in the app is the debuglog. Seems the underlying problem is the job scheduler, and not the server connection. Just guessing.

There are some bugs similar to yours. See https://github.com/signalapp/Signal-Android/issues/10693, and also the linked issues in the comments. I don't know if it could be related to the same bug.
