### ISSUE TITLE
Main device is unable to receive further messages

### ISSUE THREAD

**Issue by mintdaniel42** [mollyim/mollyim-android#290]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

When I'm using Molly as a secondary device it happens (nearly always) when I edit a message on the secondary device that the main device cannot sync new messages anymore.
[Debug from Molly](https://debuglogs.org/android/7.0.1/536b4c7879da85689466c4ce92c6987ce8a63e91f411d7c349ecf55e49dba2dc)
[Debug from Signal](https://debuglogs.org/android/7.0.2/61b303aa8411edc0850f92bcf1e8ee10de51ec585523216e158c466e70fea3a5)

### Steps to reproduce

1. Pair 2nd device
2. Edit a message on 2nd device
3. 1st device gets no new messages

### Molly version

v.7.0.1-1-Foss

### Android version

Android 12

### Device

Huawei

**Comment by bammerlaan** [comment]
I can confirm this. Also on a Huawei phone, though that's probably a coincidence?

**Comment by valldrac** [comment]
This issue should be fixed already in the latest versions.
