### ISSUE TITLE
Fails to re-register with FCM if first attempt didn't succeed

### ISSUE THREAD

**Issue by akorn** [mollyim/mollyim-android#299]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

I had firebaseinstallations.googleapis.com blocked in DNS when I first installed Molly (7.0.2-1), so it couldn't register with FCM. I unblocked it a few hours later (and notifications started working in other apps that depended on it), but even after several days and an upgrade to Molly 7.1.2-1, Molly still reported "FCM: false" in debuglog (as well as prompting to "Optimize for missing Google Play services").

(I unblocked the firebase domain at 16:07 on 2023-03-16 in case you want to cross-reference this in the debuglog.)

### Steps to reproduce

1. block firebaseinstallations.googleapis.com via DNS
2. install Molly
3. unblock firebaseinstallations.googleapis.com

### Molly version

7.1.2-1

### Android version

Android 14

### Device

Google Pixel 6pro

### Link to debug log

https://debuglogs.org/android/7.1.2/2b39467e071f283957d0cb5f3d76704e94a02bc52ead90fa1224566dc1e92f22

**Comment by valldrac** [comment]
Thank you for the report. We’re closing this issue now because, in Molly v7.21.4-1, we'll introduce an option in the app's settings to switch between FCM and websocket notifications. This will allow you to enable FCM anytime without re-registering your Signal account.
