### ISSUE TITLE
Calls on Molly v5.2.3-1-FOSS result in 'Network Failed!' message

### ISSUE THREAD

**Issue by kishanfoss** [mollyim/mollyim-android#30]
![Screenshot_20210126-203326_Molly](https://user-images.githubusercontent.com/78022471/105846000-76c08a00-5fd3-11eb-8ffc-68299fec4741.png)
Steps to reproduce
    enable either wifi or mobile data (both failed in my instance)
    Call someone on Molly

Actual result: Call fails immediately with "Network failed!"
Expected result: Call should not fail

Device info

Device: Xiaomi Mi A1
Android version: 10
Molly version: v5.2.3-1-FOSS
Location: Sarawak, Malaysia
Websocket Notifications; fully enabled (app always runs in the background)

edit: produced logfiles - in screenshots and i cant submit the logs through the submit button

**Comment by valldrac** [comment]
Hi. Do you get this error for one single contact? Or also trying to call other contacts too.
One more question. Do calls ever worked for you after updating to 5.2.3-1-FOSS?

**Comment by kishanfoss** [comment]
the same error occurs for all contacts, however after the first call had failed the subsequent call after that works fine. This issue did not occur in the version prior to v5.2.3-FOSS

**Comment by valldrac** [comment]
Many thanks for the screenshots. It is a bug in Signal https://github.com/signalapp/Signal-Android/issues/10787

I did a little troubleshooting and have some ideas about what could be the underlying problem. Let me report them to the Signal team.

**Comment by kishanfoss** [comment]
just a general proposal sir, but i suggest you to try looking over the webrtc and other related code on version 5.1.9-FOSS as i have downgraded and can confirm that calls and texts come as they should ( instantaneously) . Thank you so much for the swift help! and definitely i can say Molly is our foss beacon

**Comment by valldrac** [comment]
You are right. There is no such bug in v5.1.9.

I think I already discovered to root cause. See my [comment](https://github.com/signalapp/Signal-Android/issues/10787#issuecomment-767720996) yesterday in Signal.

**Comment by kishanfoss** [comment]
yes the TURN servers list fail to show up for websocket, they should take the effort to either remove the feature or patch it in, but its ok we users will stick to 5.19 while they take their time to fix it and you take your time to upstream it
