### ISSUE TITLE
Sock5 Proxy AUTHENTICATION REQUEST pls

### ISSUE THREAD

**Issue by sirhof** [mollyim/mollyim-android#310]
### Is there an existing request for this?

- [X] I have searched the existing issues

### Feature description

Hello devs, please can add to the poroxy sok5 the option of autentication with user and password? open a proxy sok5 without authentication its not. safe... please its hardly to make this request?
thx for the work

**Comment by valldrac** [comment]
Closing as duplicate. Please refer to #45 for the original request.
