### ISSUE TITLE
Vibration doesn't work on incoming calls

### ISSUE THREAD

**Issue by govnoebat** [mollyim/mollyim-android#313]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

When I have incoming calls my phone shows notification, even rings not in silent mode, but never vibrates.
In my phone settings vibration is allowed for Molly.

### Steps to reproduce

Enable vibration everywhere and ask someone to call

### Molly version

v7.4.2-1

### Android version

Android 13

### Device

OnePlus Nord CE3 lite

### Link to debug log

https://pastebin.com/sCtrGg3t

**Comment by govnoebat** [comment]
The same problem with Signal
https://github.com/signalapp/Signal-Android/issues/12780

**Comment by valldrac** [comment]
We’re closing this ticket as the issue has already been resolved in Signal and the bug fix has been merged into Molly.
