### ISSUE TITLE
Slower timeout for linking devices

### ISSUE THREAD

**Issue by DanVal** [mollyim/mollyim-android#314]
### Is there an existing request for this?

- [X] I have searched the existing issues

### Feature description

As described in Element: I tried to set up Molly as a linked device to my Punkt MP02 which does not have a camera, and then the device linking timeout is waaay to short to type in the UUID and pub key. When I try to do it in the signal client on desktop, it stays for multiple minutes, giving enough time. That's why I thought it would be in the app.

Thank you

**Comment by valldrac** [comment]
Thanks for reporting it. Closing by duplicate with #258
