### ISSUE TITLE
difference between molly and molly foss

### ISSUE THREAD

**Issue by userforsource** [mollyim/mollyim-android#317]
### Is there an existing request for this?

- [X] I have searched the existing issues

### Feature description

I have installed both and signal also but i find molly is slower than signal and molly foss is even slower what is the difference
Whoch i switch.

**Comment by RasheedAZ** [comment]
They already did a comparison table. Did you see this?
https://github.com/mollyim/mollyim-android?tab=readme-ov-file#dependency-comparison
