### ISSUE TITLE
Device Crashes When Using Molly

### ISSUE THREAD

**Issue by inferenceus** [mollyim/mollyim-android#318]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

Over the last week, my device crashes to bootloader and restarts. This issue seems to be occurring since the most recent Molly update I installed. This does not occur with any other app, nor Molly until the last week.

### Steps to reproduce

1. Use Molly to chat to contacts
2. Device hard-reboots after a short app hang

### Molly version

v7.4.2-1-FOSS

### Android version

Android 14 (GrapheneOS)

### Device

Google Pixel 8 Pro

### Link to debug log

https://debuglogs.org/android/7.4.2/fae8bf9357b6779a7ddbfcb61b12c6d216349c462cd35282d214ebd74e9cbbad

**Comment by RasheedAZ** [comment]
In case this is helpful, I'm getting the same thing - crash to bootloader and reboot - while using the Signal with CalyxOS. Happened 3 times last week during calls.

**Comment by inferenceus** [comment]
While I haven't experienced a crash with calls, it seems to occur whenever GIFs are posted by me to the chat. Talking with only text and sending non-GIF images/videos does not seem to crash the device.

**Comment by inferenceus** [comment]
My device crashed again just moments ago while using Molly. It happens whenever media is involved in some way, such as images being sent, or GIFs.

**Comment by valldrac** [comment]
We're closing this issue since it has been some time since it was reported. If the problem persists, please capture a new debug log and reopen this ticket.

**Comment by inferenceus** [comment]
I have been unable to reproduce this issue since my last report. I am happy to have this issue closed, as stated, as it seems to no longer be an issue.
