### ISSUE TITLE
Can't transfer account to another phone

### ISSUE THREAD

**Issue by notmentaloutlaw** [mollyim/mollyim-android#321]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

I can't transfer the account to another phone I can only restore from backup and create a new account with the older chats.

### Steps to reproduce

1. Click transfer to new phone

### Molly version

v7.6.2-2-FOSS

### Android version

14

### Device

Pixel 6,7,8

### Link to debug log

https://debuglogs.org/android/7.6.2/5b0481101da4393082fdc1d4c9b30ea22c42de851f46dcc3f78280a5c0ed4344

**Comment by taivlam** [comment]
Just as a clarifying question: are you keeping the phone number for the Signal account the same?

**Comment by colvdv** [comment]
Same issue for me
