### ISSUE TITLE
AMOLED dark mode would be cool

### ISSUE THREAD

**Issue by tomasvenrura13** [mollyim/mollyim-android#325]
### Is there an existing request for this?

- [X] I have searched the existing issues

### Feature description

It would be cool if there was another option for themes that is a deep actual real black that actually turns off the pixels with oled displays. This doesn't really save more battery but it wouldn't hurt to add. It would be a cool difference from the original app which looks identical, as an option of course.

**Comment by tomasventura13** [comment]
I know someone has said this before, but it really can't be all THAT hard to change some hex codes right.

**Comment by tomasvenrura13** [comment]
I know someone has said this before, but it really can't be all THAT hard to change some hex codes right

**Comment by valldrac** [comment]
Thanks for the suggestion. This feature is already being tracked in #309. Please follow that for updates.

Closing this as duplicate.
