### ISSUE TITLE
Google ReCAPTCHA

### ISSUE THREAD

**Issue by abh-oss01** [mollyim/mollyim-android#33]
I just reinstalled Molly `v5.3.12-1-FOSS` and while signing in, it asked me to prove I'm a human, and surprisingly enough, I had to solve a ReCAPTCHA puzzle, which is from **Google**.

As a Molly Foss is a FOSS app, I felt a bit shocked to see that there, any reasons as to why Molly uses Google' ReCAPTCHA, instead of hCAPTCHA?

![Screenshot_2021-02-09-15-02-49-13_1.jpg](https://user-images.githubusercontent.com/56572179/107344697-c0879500-6ae8-11eb-92da-10f112bb03bb.jpg)

**Comment by valldrac** [comment]
I know. But it is a requirement of the Signal servers. I cannot replace it.

For what it is worth, the captcha is loaded as a web page, so still Molly-FOSS is free of non-free code.
