### ISSUE TITLE
Gradle Build Fails with ArtifactResolveException for Configuration ':app

### ISSUE THREAD

**Issue by monospare** [mollyim/mollyim-android#331]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

I am encountering an issue while building the Molly app using Gradle. The build fails consistently with the following error message:

`Caused by: org.gradle.api.internal.artifacts.ivyservice.DefaultLenientConfiguration$ArtifactResolveException: Could not resolve all files for configuration ':app:prodGmsWebsiteDebugCompileClasspath'.
`

I have tried various solutions, including cleaning the project, invalidating caches, and reinstalling dependencies, but none of these have resolved the issue.

unable to paste here complete errors due to maximum characters reach , you can check the entire errors text here on this clipboard - https://share.vichaaro.com/H6wL

### Steps to reproduce

1. Clone the Molly app repository.

2.Open the project in Android Studio.

3. Try to build the project through Android Studio.

Android Studio Versions: Jellyfish, Hedgehog, Iguana, Giraffe
Gradle Version: 8.0.2
Operating System: Windows 11

I tried different android studio versions like  Jellyfish, Hedgehog, Iguana, Giraffe, None of the above versions worked for me. Could you please suggest which version of Android Studio and Gradle should be used to successfully build the project?

### Molly version

v7.8.1-1

### Android version

Android 13

**Comment by valldrac** [comment]
It's failing because it can't access to this package:

https://raw.githubusercontent.com/mollyim/maven/master/argon2/releases/im/molly/argon2/13.1-1/argon2-13.1-1.pom 

Make sure your network connection is working.
