### ISSUE TITLE
Unlock crash: ForegroundService fails to start 

### ISSUE THREAD

**Issue by mazingerbogdanov** [mollyim/mollyim-android#333]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

Hi,
When I try to unlock Molly, entering my passphrase and completing the biometric verification, the app tends to break. This happens the 2/3 times that I try to unlock.
I use Orbot to connect, and I have it connected all the time. When the app crashes, a message telling that Orbot has initiated appears in the screen.

**Debug log**
[molly-log-1717578595810.zip](https://github.com/user-attachments/files/15585879/molly-log-1717578595810.zip)

### Steps to reproduce

1. Connect to Tor net via Orbot and open Molly
2. Unlock Molly

### Molly version

v7.8.1-1.up1-FOSS

### Android version

Android 12

### Device

Xiaomi Redmi Note 9

**Comment by valldrac** [comment]
Thanks for the bug report. A fix will be included in Molly v7.21.4-1, which should resolve the crash.
