### ISSUE TITLE
[BUG] Scheduled messages does not work

### ISSUE THREAD

**Issue by BAXSD** [mollyim/mollyim-android#334]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

I tested sending an scheduled message. When the time had past for the message to be sent and when I opened Molly it showed the message was sent "**JUST NOW**" and was never sent at the time it was supposed to be sent . Does this happen because of the database is locked and at rest or is it a bug?

### Steps to reproduce

1. Send an scheduled message.
2. Close Molly and database locked and at rest.
3. Open Molly after the message should have been sent.
4. Molly shows the message sent "**JUST NOW**"

### Molly version

Molly-v7.8.1-1

### Android version

Android 14

### Device

Samsung Galaxy S23 Ultra

**Comment by valldrac** [comment]
Sorry for the late reply. This is actually the expected behavior when Molly is locked and at rest. The app is not able to send scheduled messages when locked.
