### ISSUE TITLE
Customize backup interval and number of stored backups

### ISSUE THREAD

**Issue by SailReal** [mollyim/mollyim-android#34]
As a user, it would be perfect if you could customize the backup interval and the number of stored backups.

My database of Molly is 8 GB, two times the backup file makes a total of 24 GB of disk space consumed. Currently two backup files are stored, one is created every day. While creating the backup, a third file is used, the oldest is deleted when finished. That means, in my case 32 GB of disk space is consumed for a short time...on a smartphone, that's quite a lot, even the 24 GB permanently.

For me it would be enough if there is only one backup file and if it is overwritten only once a week.

btw: thanks for this awesome product :+1:

**Comment by valldrac** [comment]
Make sense.

Have you discussed this feature with the Signal developers? I searched the user community forum and it seems it was requested time ago. I wonder if there is any pull-request already open to the official Signal.

**Comment by SailReal** [comment]
> Have you discussed this feature with the Signal developers?

No, I searched the user community forum as well but to me it didn't seem like it had any prio for the signal devs and I guess it's relatively easy to implement. Even a complete manual backup would be enough: Backup turned on but no automatic backup, just create a new one by clicking on `Create Backup`.
