### ISSUE TITLE
What end has made MobileCoin (MOB) wallet in Signal/Molly?

### ISSUE THREAD

**Issue by serrq** [mollyim/mollyim-android#343]
### Is there an existing request for this?

- [X] I have searched the existing issues

### Feature description

Time ago I installed Signal and it had a wallet within that held MOB cryptocurrency.

What did it happen with it?

I loss something in the meanwhile?

**Comment by valldrac** [comment]
Sorry for the confusion. From the beginning, Molly did not support MobileCoin. But if you install Signal, your coins should still be there.

**Comment by valldrac** [comment]
> Will Molly support some coin (wallet) in the future?

Yes, we are working to integrate Monero in Molly, as a replacement for MobileCoin, with funding from the Monero community crowdfunding.
