### ISSUE TITLE
I cannot finding the backup manager: where is it?

### ISSUE THREAD

**Issue by serrq** [mollyim/mollyim-android#344]
### Is there an existing request for this?

- [X] I have searched the existing issues

### Feature description

I am sorry, I cannot finding the backup manager feature in the latest build (fdroid molly repo).

Someone might helps me?

**Comment by taivlam** [comment]
First, this should apply to all versions of Molly and this should be the menu flow: start from the main Molly screen of all conversations > tap the three vertical dots in the upper right corner > select "Settings" > Select "Chats" > select "Chat backups" under "Backups".

(BTW, chat backups settings in Molly are in the same place as the normal Signal Android app.  The only Molly-unique options for chat backups are to schedule the time between daily and weekly; and determining the max number of backups to keep.)

Second, I think the label of "question" would be more accurate.

**Comment by taivlam** [comment]
* I used Signal (the [web APK](https://signal.org/android/apk/)) before I discovered Molly; and I also use both side-by-side on the same user profile in Android.  So, I'm able to compare both.
* Since this GH issue is already created, I think only a maintainer of this repo or the Molly org is able to change the label for this issue.

**Comment by taivlam** [comment]
If I'm understanding correctly, then I'm not sure if that is really possible.

Maybe the size of those 3 dots can be changed increasing the UI size in Android system Settings app and going on this UX path:

the Settings app > Display > select "Display size and text" under Appearance > use the slider for "Display size"

This screen shot is what the top of Molly looks for me:
![screenshot1](https://github.com/user-attachments/assets/bca60fc6-e4cc-4b77-94ab-6d705dcaaa85)
