### ISSUE TITLE
Remove unnecessary permissions

### ISSUE THREAD

**Issue by hrj** [mollyim/mollyim-android#35]
Similar to #23 but coming from a different requirement: Would it be possible to create a flavour with fewer permissions, especially the non-deniable permissions?

For example, these seem non-criticial because I can get the same functionality from OS settings:

* "change network connectivity"
* "connect and disconnect from wifi"
* "pair with bluetooth devices"
* "set wallpaper"
* "view network connections"
* "view wifi connections"

**Comment by valldrac** [comment]
The app needs the Bluetooth permission for video calls, to pair with audio headsets.

Regarding the network permissions, there are some settings that depends on then. See https://support.signal.org/hc/en-us/articles/360056044831-Data-Usage-Options-Wi-Fi-Cellular-jobs-

But the app doesn't make any changes to the connectivity of the device, or the WiFi. So I guess some permissions are not needed at all and can be removed. I have to take a look at it.

**Comment by hrj** [comment]
> The app needs the Bluetooth permission for video calls, to pair with audio headsets.

As an alternate, couldn't the user pair with their headset system wide? Then all audio will be routed to the headset, and the apps needn't bother about it? (Genuine question; I don't have BT headsets, but this is how I am imagining BT headsets would work)

**Comment by hrj** [comment]
> Regarding the network permissions, there are some settings that depends on them. See https://support.signal.org/hc/en-us/articles/360056044831-Data-Usage-Options-Wi-Fi-Cellular-jobs-

Reading through the docs, it looks like `ACCESS_NETWORK_STATE` is sufficient to get information about the type of the network. From API 21 onwards, [getNetworkCapabilites](https://developer.android.com/reference/android/net/ConnectivityManager#getNetworkCapabilities(android.net.Network)) can be used.

**Comment by valldrac** [comment]
The new device transfer feature via Wifi Direct, introduced in Signal v.5.5.0, requires some of the removed permissions, according to https://developer.android.com/training/connect-devices-wirelessly/wifi-direct. I had to add the following permissions again:

- ACCESS_WIFI_STATE
- CHANGE_WIFI_STATE
- CHANGE_NETWORK_STATE
