### ISSUE TITLE
Link to existing device broken with Signal Beta (7.11.2)

### ISSUE THREAD

**Issue by cmeyer231** [mollyim/mollyim-android#351]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

When using the non-beta version of signal the linking works as expected. When beta version is installed the linking fails on the Molly side, giving the error "Timed out waiting for the primary device." with the option to retry. No error on the Signal side, but device does not show up in linked devices.

Linking the beta version of Signal to the desktop app (7.15.0) works as expected.

Changes in the linked devices interface are listed in the change logs of the latest beta version.

### Steps to reproduce

1. Install beta version of Signal on main device
2. Install Molly 7.8.1.2 on second device
3. Try and link Molly to the beta Signal

### Molly version

7.8.1.2

### Android version

Android 14

### Device

S22 Ultra

**Comment by denizt** [comment]
I had this problem with my device and had a look at this one. This happens because the newer versions allow deleteSync capability which molly doesn't. I [added the flag](https://github.com/denizt/mollyim-android/commit/4eb757aea09dfcaed6f7cfd7b4d88aa7713015f2) for debugging and was able to link, there is more information in the commit.

**Comment by fogame234** [comment]
I'm not running the beta version and cannot link a shared device.

**Comment by denizt** [comment]
I think they rolled out `deletesync` to stable, I have desktop 7.1.6 on macOS and it did say _'your deleted conversations will be synced'_ when I tried to delete a message.

**Comment by fogame234** [comment]
> I think they rolled out `deletesync` to stable, I have desktop 7.1.6 on macOS and it did say _'your deleted conversations will be synced'_ when I tried to delete a message.

I'd say that's pretty accurate. I was able to connect to a windows and linux desktop just fine.

**Comment by tazz4843** [comment]
Can confirm this is broken on stable Signal. My main device is an iPhone on iOS 18 public beta 1 running Signal 7.18 (190) and I get the timed out linking error on my Pixel 7a running GrapheneOS (Android 14) with Molly v7.8.1-2.

**Comment by denizt** [comment]
What is the process for fixing issues @valldrac? Is there a tracker to follow this up except github? I could have a look at it if I can find the time, but considering it's a sizeable change, I don't want to duplicate work 😄

**Comment by valldrac** [comment]
The fix is almost ready, so with the branch `molly-7.11` you can register as a linked device again. However, some things like syncing the avatar and some settings might still have issues. There's also a lot more testing needed.
