### ISSUE TITLE
Molly can't start after update to 7.12.3.2 and crashes

### ISSUE THREAD

**Issue by dill-shower** [mollyim/mollyim-android#356]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

08-04 20:57:42.029 15541 15541 I im.molly.app: Using CollectorTypeCMC GC.
08-04 20:57:42.035 15541 15541 E im.molly.app: Not starting debugger since process cannot load the jdwp agent.
08-04 20:57:42.087 15541 15541 W libc    : Access denied finding property "ro.debuggable"
08-04 20:57:42.098 15541 15541 W libc    : Access denied finding property "ro.debuggable"
08-04 20:57:42.098 15541 15541 D AndroidRuntime: >>>>>> START com.android.internal.os.RuntimeInit uid 10142 <<<<<<
08-04 20:57:42.098 15541 15541 W libc    : Access denied finding property "ro.debuggable"
08-04 20:57:42.102 15541 15541 I AndroidRuntime: Using default boot image
08-04 20:57:42.102 15541 15541 I AndroidRuntime: Leaving lock profiling enabled
08-04 20:57:42.102 15541 15541 W libc    : Access denied finding property "odsign.verification.success"
08-04 20:57:42.102 15541 15541 W libc    : Access denied finding property "ro.debuggable"
08-04 20:57:42.102 15541 15541 E cutils-trace: Error opening trace file: No such file or directory (2)
08-04 20:57:42.104 15541 15541 W im.molly.app: ART APEX data files are untrusted.
08-04 20:57:42.104 15541 15541 I im.molly.app: Using CollectorTypeCMC GC.
08-04 20:57:42.170 15541 15541 D nativeloader: InitDefaultPublicLibraries for_preload=1: libandroid.so:libaaudio.so:libamidi.so:libbinder_ndk.so:libc.so:libcamera2ndk.so:libdl.so:libEGL.so:libGLESv1_CM.so:libGLESv2.so:libGLESv3.so:libicu.so:libicui18n.so:libicuuc.so:libjnigraphics.so:liblog.so:libmediandk.so:libm.so:libnativehelper.so:libnativewindow.so:libOpenMAXAL.so:libOpenSLES.so:libRS.so:libstdc++.so:libsync.so:libvulkan.so:libwebviewchromium_plat_support.so:libz.so
08-04 20:57:42.177 15541 15541 D nativeloader: Load libicu_jni.so using APEX ns com_android_art for caller /apex/com.android.art/javalib/core-oj.jar: ok
08-04 20:57:42.177 15541 15541 D im.molly.app: Time zone APEX ICU file found: /apex/com.android.tzdata/etc/icu/icu_tzdata.dat
08-04 20:57:42.177 15541 15541 D im.molly.app: I18n APEX ICU file found: /apex/com.android.i18n/etc/icu/icudt72l.dat
08-04 20:57:42.178 15541 15541 D nativeloader: Load libjavacore.so using APEX ns com_android_art for caller /apex/com.android.art/javalib/core-oj.jar: ok
08-04 20:57:42.179 15541 15541 D nativeloader: Load libopenjdk.so using APEX ns com_android_art for caller /apex/com.android.art/javalib/core-oj.jar: ok
08-04 20:57:42.200 15541 15541 W libc    : Access denied finding property "ro.product.name_for_attestation"
08-04 20:57:42.200 15541 15541 W libc    : Access denied finding property "ro.product.device_for_attestation"
08-04 20:57:42.200 15541 15541 W libc    : Access denied finding property "ro.product.manufacturer_for_attestation"
08-04 20:57:42.200 15541 15541 W libc    : Access denied finding property "ro.product.brand_for_attestation"
08-04 20:57:42.201 15541 15541 D nativeloader: Load libframework-connectivity-tiramisu-jni.so using APEX ns com_android_tethering for caller /apex/com.android.tethering/javalib/framework-connectivity-t.jar: ok
08-04 20:57:42.202 15541 15541 D AndroidRuntime: Calling main entry com.android.internal.os.ExecInit
08-04 20:57:42.202 15541 15541 D Zygote  : begin preload
08-04 20:57:42.202 15541 15541 I Zygote  : Calling ZygoteHooks.beginPreload()
08-04 20:57:42.219 15541 15541 I Zygote  : Preloading shared libraries...
08-04 20:57:42.219 15541 15541 D nativeloader: Load libandroid.so using system ns (caller=/system/framework/framework.jar!classes5.dex): ok
08-04 20:57:42.220 15541 15541 D nativeloader: Load libjnigraphics.so using system ns (caller=/system/framework/framework.jar!classes5.dex): ok
08-04 20:57:42.220 15541 15541 D nativeloader: Load libcompiler_rt.so using system ns (caller=/system/framework/framework.jar!classes5.dex): ok
08-04 20:57:42.220 15541 15541 E im.molly.app: Unable to find pattern file or unable to map it for am
08-04 20:57:42.221 15541 15541 I Zygote  : Called ZygoteHooks.endPreload()
08-04 20:57:42.223 15541 15541 D nativeloader: Load libjavacrypto.so using APEX ns com_android_conscrypt for caller /apex/com.android.conscrypt/javalib/conscrypt.jar: ok
08-04 20:57:42.227 15541 15541 I Zygote  : Installed AndroidKeyStoreProvider in 6ms.
08-04 20:57:42.227 15541 15541 D Zygote  : end preload
08-04 20:57:42.233 15541 15570 W libc    : Access denied finding property "qemu.sf.lcd_density"
08-04 20:57:42.233 15541 15570 W libc    : Access denied finding property "qemu.sf.lcd_density"
08-04 20:57:42.239 15541 15541 D nativeloader: Load libstats_jni.so using APEX ns com_android_os_statsd for caller /apex/com.android.os.statsd/javalib/framework-statsd.jar: ok
08-04 20:57:42.239 15541 15541 D CompatibilityChangeReporter: Compat change id reported: 171979766; UID 10142; state: ENABLED
08-04 20:57:42.239 15541 15541 D CompatibilityChangeReporter: Compat change id reported: 242716250; UID 10142; state: DISABLED
08-04 20:57:42.240 15541 15541 I Typeface: Preloading /system/fonts/Roboto-Regular.ttf
08-04 20:57:42.240 15541 15541 I Typeface: Preloading /system/fonts/RobotoStatic-Regular.ttf
08-04 20:57:42.241 15541 15541 I SystemFonts: Loading font config from /system/etc/fonts.xml
08-04 20:57:42.242 15541 15541 D CompatibilityChangeReporter: Compat change id reported: 247079863; UID 10142; state: DISABLED
08-04 20:57:42.263 15541 15541 D nativeloader: InitApexLibraries:
08-04 20:57:42.263 15541 15541 D nativeloader:   com_android_art: libnativehelper.so
08-04 20:57:42.263 15541 15541 D nativeloader:   com_android_i18n: libicui18n.so:libicuuc.so:libicu.so
08-04 20:57:42.263 15541 15541 D nativeloader:   com_android_neuralnetworks: libneuralnetworks.so
08-04 20:57:42.263 15541 15541 D nativeloader: InitDefaultPublicLibraries for_preload=0: libandroid.so:libaaudio.so:libamidi.so:libbinder_ndk.so:libc.so:libcamera2ndk.so:libclang_rt.hwasan-aarch64-android.so:libdl.so:libEGL.so:libGLESv1_CM.so:libGLESv2.so:libGLESv3.so:libjnigraphics.so:liblog.so:libmediandk.so:libm.so:libnativewindow.so:libOpenMAXAL.so:libOpenSLES.so:libRS.so:libstdc++.so:libsync.so:libvulkan.so:libwebviewchromium_plat_support.so:libz.so
08-04 20:57:42.263 15541 15541 D nativeloader: Configuring clns-1 for other apk /system/framework/org.apache.http.legacy.jar. target_sdk_version=33, uses_libraries=ALL, library_path=/data/app/~~63QBXk22w8feF9GpNzGCRA==/im.molly.app-nk7ZS-MUuDE9j-GhM6bNIQ==/lib/arm64:/data/app/~~63QBXk22w8feF9GpNzGCRA==/im.molly.app-nk7ZS-MUuDE9j-GhM6bNIQ==/base.apk!/lib/arm64-v8a, permitted_path=/data:/mnt/expand:/data/user/0/im.molly.app
08-04 20:57:42.263 15541 15541 D nativeloader: InitExtendedPublicLibraries: libedgetpu_dba.google.so
08-04 20:57:42.263 15541 15541 D nativeloader: Extending system_exposed_libraries: libedgetpu_dba.google.so
08-04 20:57:42.264 15541 15541 D nativeloader: InitVendorPublicLibraries: libOpenCL.so:libOpenCL-pixel.so:libedgetpu_client.google.so:libedgetpu_util.so:lib_aion_buffer.so:lib_jpg_encoder.so:libgxp.so
08-04 20:57:42.264 15541 15541 D nativeloader: InitProductPublicLibraries: 
08-04 20:57:42.264 15541 15541 D nativeloader: Configuring clns-2 for other apk /system_ext/framework/com.google.android.camerax.extensions.jar. target_sdk_version=33, uses_libraries=ALL, library_path=/data/app/~~63QBXk22w8feF9GpNzGCRA==/im.molly.app-nk7ZS-MUuDE9j-GhM6bNIQ==/lib/arm64:/data/app/~~63QBXk22w8feF9GpNzGCRA==/im.molly.app-nk7ZS-MUuDE9j-GhM6bNIQ==/base.apk!/lib/arm64-v8a, permitted_path=/data:/mnt/expand:/data/user/0/im.molly.app
08-04 20:57:42.264 15541 15541 D nativeloader: Extending system_exposed_libraries: libedgetpu_dba.google.so
08-04 20:57:42.265 15541 15541 D nativeloader: Configuring clns-3 for other apk /system_ext/framework/androidx.window.extensions.jar. target_sdk_version=33, uses_libraries=ALL, library_path=/data/app/~~63QBXk22w8feF9GpNzGCRA==/im.molly.app-nk7ZS-MUuDE9j-GhM6bNIQ==/lib/arm64:/data/app/~~63QBXk22w8feF9GpNzGCRA==/im.molly.app-nk7ZS-MUuDE9j-GhM6bNIQ==/base.apk!/lib/arm64-v8a, permitted_path=/data:/mnt/expand:/data/user/0/im.molly.app
08-04 20:57:42.265 15541 15541 D nativeloader: Extending system_exposed_libraries: libedgetpu_dba.google.so
08-04 20:57:42.266 15541 15541 D nativeloader: Configuring clns-4 for other apk /system_ext/framework/androidx.window.sidecar.jar. target_sdk_version=33, uses_libraries=ALL, library_path=/data/app/~~63QBXk22w8feF9GpNzGCRA==/im.molly.app-nk7ZS-MUuDE9j-GhM6bNIQ==/lib/arm64:/data/app/~~63QBXk22w8feF9GpNzGCRA==/im.molly.app-nk7ZS-MUuDE9j-GhM6bNIQ==/base.apk!/lib/arm64-v8a, permitted_path=/data:/mnt/expand:/data/user/0/im.molly.app
08-04 20:57:42.266 15541 15541 D nativeloader: Extending system_exposed_libraries: libedgetpu_dba.google.so
08-04 20:57:42.269 15541 15541 D nativeloader: Configuring clns-5 for other apk /data/app/~~63QBXk22w8feF9GpNzGCRA==/im.molly.app-nk7ZS-MUuDE9j-GhM6bNIQ==/base.apk. target_sdk_version=33, uses_libraries=, library_path=/data/app/~~63QBXk22w8feF9GpNzGCRA==/im.molly.app-nk7ZS-MUuDE9j-GhM6bNIQ==/lib/arm64:/data/app/~~63QBXk22w8feF9GpNzGCRA==/im.molly.app-nk7ZS-MUuDE9j-GhM6bNIQ==/base.apk!/lib/arm64-v8a, permitted_path=/data:/mnt/expand:/data/user/0/im.molly.app
08-04 20:57:42.273 15541 15541 D nativeloader: Load libframework-connectivity-jni.so using APEX ns com_android_tethering for caller /apex/com.android.tethering/javalib/framework-connectivity.jar: ok
08-04 20:57:42.274 15541 15541 V GraphicsEnvironment: Currently set values for:
08-04 20:57:42.274 15541 15541 V GraphicsEnvironment:   angle_gl_driver_selection_pkgs=[com.android.angle, com.linecorp.b612.android, com.campmobile.snow, com.google.android.apps.tachyon]
08-04 20:57:42.274 15541 15541 V GraphicsEnvironment:   angle_gl_driver_selection_values=[angle, native, native, native]
08-04 20:57:42.274 15541 15541 V GraphicsEnvironment: im.molly.app is not listed in per-application setting
08-04 20:57:42.274 15541 15541 V GraphicsEnvironment: Neither updatable production driver nor prerelease driver is supported.
08-04 20:57:42.280 15541 15541 I MultiDex: VM with version 2.1.0 has multidex support
08-04 20:57:42.280 15541 15541 I MultiDex: Installing application
08-04 20:57:42.280 15541 15541 I MultiDex: VM has multidex support, MultiDex support library is disabled.
08-04 20:57:42.283 15541 15541 D CompatibilityChangeReporter: Compat change id reported: 279646685; UID 10142; state: DISABLED
08-04 20:57:42.286 15541 15541 I ApplicationContext: onCreate()
08-04 20:57:42.287 15541 15541 D nativeloader: Load /data/app/~~63QBXk22w8feF9GpNzGCRA==/im.molly.app-nk7ZS-MUuDE9j-GhM6bNIQ==/lib/arm64/libsqlcipher.so using ns clns-5 from class loader (caller=<unknown>): ok
08-04 20:57:42.287 15541 15541 D DynamicTheme: Setting to follow system expecting: 32
08-04 20:57:42.287 15541 15541 D CachedInflater: Clearing view cache.
08-04 20:57:42.288 15541 15541 D ScreenLockController: Auto-lock disabled
08-04 20:57:42.289 15541 15541 I ApplicationContext: onUnlock()
08-04 20:57:42.333 15541 15541 D nativeloader: Load /data/app/~~63QBXk22w8feF9GpNzGCRA==/im.molly.app-nk7ZS-MUuDE9j-GhM6bNIQ==/lib/arm64/libsignal_jni.so using ns clns-5 from class loader (caller=<unknown>): ok
08-04 20:57:42.335 15541 15541 D nativeloader: Load /data/app/~~63QBXk22w8feF9GpNzGCRA==/im.molly.app-nk7ZS-MUuDE9j-GhM6bNIQ==/lib/arm64/libaesgcm.so using ns clns-5 from class loader (caller=<unknown>): ok
08-04 20:57:42.336 15541 15541 D nativeloader: Load /data/app/~~63QBXk22w8feF9GpNzGCRA==/im.molly.app-nk7ZS-MUuDE9j-GhM6bNIQ==/lib/arm64/libconscrypt_jni.so using ns clns-5 from class loader (caller=<unknown>): ok
08-04 20:57:42.336 15541 15541 V NativeCrypto: Registering org/conscrypt/NativeCrypto's 288 native methods...
08-04 20:57:42.337 15541 15579 I SQLiteConnection: Database keying operation returned:0
08-04 20:57:42.340 15541 15579 I SQLiteConnection: Database keying operation returned:0
08-04 20:57:42.346 15541 15541 I SQLiteConnection: Database keying operation returned:0
08-04 20:57:42.348 15541 15541 I SQLiteConnection: Database keying operation returned:0
08-04 20:57:42.348 15541 15579 I WebViewFactory: Loading app.vanadium.webview version 126.0.6478.122.3 (code 647812533)
08-04 20:57:42.350 15541 15580 I SQLiteConnection: Database keying operation returned:0
08-04 20:57:42.352 15541 15579 W ziparchive: Unable to open '/product/app/TrichromeLibrary/TrichromeLibrary.dm': No such file or directory
08-04 20:57:42.352 15541 15579 W ziparchive: Unable to open '/product/app/TrichromeLibrary/TrichromeLibrary.dm': No such file or directory
08-04 20:57:42.352 15541 15579 W im.molly.app: Entry not found
08-04 20:57:42.353 15541 15579 D nativeloader: InitLlndkLibrariesProduct: libEGL.so:libGLESv1_CM.so:libGLESv2.so:libGLESv3.so:libRS.so:libandroid_net.so:libapexsupport.so:libbinder_ndk.so:libc.so:libcgrouprc.so:libclang_rt.asan-aarch64-android.so:libclang_rt.hwasan-aarch64-android.so:libcom.android.tethering.connectivity_native.so:libdl.so:libft2.so:liblog.so:libm.so:libmediandk.so:libnativewindow.so:libneuralnetworks.so:libselinux.so:libsync.so:libvendorsupport.so:libvndksupport.so:libvulkan.so
08-04 20:57:42.353 15541 15579 D nativeloader: Configuring product-clns-6 for unbundled product apk /product/app/TrichromeLibrary/TrichromeLibrary.apk. target_sdk_version=35, uses_libraries=ALL, library_path=/product/app/TrichromeWebView/lib/arm64:/product/app/TrichromeWebView/TrichromeWebView.apk!/lib/arm64-v8a:/product/app/TrichromeLibrary/TrichromeLibrary.apk!/lib/arm64-v8a:/product/lib64:/system/product/lib64, permitted_path=/data:/mnt/expand:/product/lib64:/system/product/lib64
08-04 20:57:42.353 15541 15579 D nativeloader: Extending system_exposed_libraries: libedgetpu_dba.google.so
08-04 20:57:42.354 15541 15579 D nativeloader: InitVndkspLibrariesProduct: VNDK is deprecated with product
08-04 20:57:42.354 15541 15580 I SQLiteConnection: Database keying operation returned:0
08-04 20:57:42.356 15541 15579 D nativeloader: Configuring product-clns-7 for unbundled product apk /product/app/TrichromeWebView/TrichromeWebView.apk. target_sdk_version=35, uses_libraries=, library_path=/product/app/TrichromeWebView/lib/arm64:/product/app/TrichromeWebView/TrichromeWebView.apk!/lib/arm64-v8a:/product/app/TrichromeLibrary/TrichromeLibrary.apk!/lib/arm64-v8a:/product/lib64:/system/product/lib64, permitted_path=/data:/mnt/expand:/product/lib64:/system/product/lib64
08-04 20:57:42.358 15541 15579 E WebViewLibraryLoader: can't load with relro file; address space not reserved
08-04 20:57:42.360 15541 15579 I cr_WVCFactoryProvider: version=126.0.6478.122 (647812533) minSdkVersion=29 isBundle=false multiprocess=true packageId=2
08-04 20:57:42.361 15541 15579 W cr_VanadiumConfParser: not initializing parsing with unverified config package
08-04 20:57:42.365 15541 15585 I SQLiteConnection: Database keying operation returned:0
08-04 20:57:42.369 15541 15585 I SQLiteConnection: Database keying operation returned:0
08-04 20:57:42.377 15541 15541 D CallManager: Loading ringrtc library
08-04 20:57:42.377 15541 15579 D nativeloader: Load /product/app/TrichromeLibrary/TrichromeLibrary.apk!/lib/arm64-v8a/libmonochrome_64.so using ns product-clns-7 from class loader (caller=<unknown>): ok
08-04 20:57:42.378 15541 15579 E cr_VanadiumConfigBridge: Config app not parsed nor initialized, returning early
08-04 20:57:42.380 15541 15541 D nativeloader: Load /data/app/~~63QBXk22w8feF9GpNzGCRA==/im.molly.app-nk7ZS-MUuDE9j-GhM6bNIQ==/lib/arm64/libringrtc.so using ns clns-5 from class loader (caller=<unknown>): ok
08-04 20:57:42.380 15541 15579 D nativeloader: Load /system/lib64/libwebviewchromium_plat_support.so using ns product-clns-7 from class loader (caller=<unknown>): ok
08-04 20:57:42.381 15541 15541 I org.webrtc.Logging: NativeLibrary: Loading native library: jingle_peerconnection_so
08-04 20:57:42.385 15541 15589 W libc    : Access denied finding property "ro.debuggable"
08-04 20:57:42.392 15541 15595 I SQLiteConnection: Database keying operation returned:0
08-04 20:57:42.392 15541 15589 D CompatibilityChangeReporter: Compat change id reported: 160794467; UID 10142; state: ENABLED
08-04 20:57:42.395 15541 15595 I SQLiteConnection: Database keying operation returned:0
08-04 20:57:42.398 15541 15590 I SQLiteConnection: Database keying operation returned:0
--------- switch to crash
08-04 20:57:42.398 15541 15580 E AndroidRuntime: FATAL EXCEPTION: signal-bounded-0
08-04 20:57:42.398 15541 15580 E AndroidRuntime: Process: im.molly.app, PID: 15541
08-04 20:57:42.398 15541 15580 E AndroidRuntime: org.json.JSONException: Value null at attachmentId of type org.json.JSONObject$1 cannot be converted to JSONObject
08-04 20:57:42.398 15541 15580 E AndroidRuntime: 	at org.json.JSON.typeMismatch(JSON.java:101)
08-04 20:57:42.398 15541 15580 E AndroidRuntime: 	at org.json.JSONObject.getJSONObject(JSONObject.java:622)
08-04 20:57:42.398 15541 15580 E AndroidRuntime: 	at org.thoughtcrime.securesms.database.helpers.migration.V238_AddGroupSendEndorsementsColumns.migrate(V238_AddGroupSendEndorsementsColumns.kt:46)
08-04 20:57:42.398 15541 15580 E AndroidRuntime: 	at org.thoughtcrime.securesms.database.helpers.SignalDatabaseMigrations$migrate$1.invoke(SignalDatabaseMigrations.kt:217)
08-04 20:57:42.398 15541 15580 E AndroidRuntime: 	at org.thoughtcrime.securesms.database.helpers.SignalDatabaseMigrations$migrate$1.invoke(SignalDatabaseMigrations.kt:216)
08-04 20:57:42.398 15541 15580 E AndroidRuntime: 	at org.signal.core.util.SQLiteDatabaseExtensionsKt.withinTransaction(SQLiteDatabaseExtensions.kt:19)
08-04 20:57:42.398 15541 15580 E AndroidRuntime: 	at org.thoughtcrime.securesms.database.helpers.SignalDatabaseMigrations.migrate(SignalDatabaseMigrations.kt:216)
08-04 20:57:42.398 15541 15580 E AndroidRuntime: 	at org.thoughtcrime.securesms.database.SignalDatabase.onUpgrade(SignalDatabase.kt:158)
08-04 20:57:42.398 15541 15580 E AndroidRuntime: 	at net.zetetic.database.sqlcipher.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:403)
08-04 20:57:42.398 15541 15580 E AndroidRuntime: 	at net.zetetic.database.sqlcipher.SQLiteOpenHelper.getReadableDatabase(SQLiteOpenHelper.java:302)
08-04 20:57:42.398 15541 15580 E AndroidRuntime: 	at org.thoughtcrime.securesms.database.SignalDatabase.getRawReadableDatabase(SignalDatabase.kt:179)
08-04 20:57:42.398 15541 15580 E AndroidRuntime: 	at org.thoughtcrime.securesms.database.SignalDatabase$Companion.hasTable(SignalDatabase.kt:295)
08-04 20:57:42.398 15541 15580 E AndroidRuntime: 	at org.thoughtcrime.securesms.database.SignalDatabase.hasTable(SignalDatabase.kt:0)
08-04 20:57:42.398 15541 15580 E AndroidRuntime: 	at org.thoughtcrime.securesms.database.KeyValueDatabase.lambda$onOpen$0(KeyValueDatabase.java:106)
08-04 20:57:42.398 15541 15580 E AndroidRuntime: 	at org.thoughtcrime.securesms.database.KeyValueDatabase.$r8$lambda$G2dZI_gAXkqExOGYLgmndIoi47k(KeyValueDatabase.java:0)
08-04 20:57:42.398 15541 15580 E AndroidRuntime: 	at org.thoughtcrime.securesms.database.KeyValueDatabase$$ExternalSyntheticLambda0.run(R8$$SyntheticClass:0)
08-04 20:57:42.398 15541 15580 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
08-04 20:57:42.398 15541 15580 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
08-04 20:57:42.398 15541 15580 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:1012)
08-04 20:57:42.398 15541 15580 E AndroidRuntime: 	at org.signal.core.util.concurrent.SignalExecutors$NumberedThreadFactory$1.run(SignalExecutors.java:109)
--------- switch to main
08-04 20:57:42.401 15541 15541 E cr_VanadiumConfigBridge: Config app not parsed nor initialized, returning early
08-04 20:57:42.403 15541 15541 I cr_LibraryLoader: Successfully loaded native library
08-04 20:57:42.403 15541 15541 I cr_CachingUmaRecorder: Flushed 7 samples from 7 histograms, 0 samples were dropped.
08-04 20:57:42.410 15541 15541 I cr_CombinedPProvider: #registerProvider() provider:WV.N6@e0f77a6 isPolicyCacheEnabled:false policyProvidersSize:0
08-04 20:57:42.412 15541 15590 I SQLiteConnection: Database keying operation returned:0
08-04 20:57:42.414 15541 15541 I cr_PolicyProvider: #setManagerAndSource() 0
08-04 20:57:42.415 15541 15580 I Process : Sending signal. PID: 15541 SIG: 9

### Steps to reproduce

1.
2.

### Molly version

7.12.3.2-FOSS 

### Android version

GrapheneOS

### Device

Pixel

**Comment by Snuupy** [comment]
same, forced downgrade leads to crashing too

**Comment by valldrac** [comment]
Thanks for the report. We’ve released a new beta v7.12.3-3 that should fix the crash.

Let us know if you have any other issues!

**Comment by dill-shower** [comment]
Thank you for the quick fix
