### ISSUE TITLE
can not update old version to v7.12.3-3 

### ISSUE THREAD

**Issue by safarifox** [mollyim/mollyim-android#357]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

i have v7.8.1-2-FOSS installed.. 
when im traying to update app to v7.12.3-3 (FOSS) im getting installation failed

### Steps to reproduce

1. Install v7.8.1-2-FOSS 
2. update to  v7.12.3-3 (FOSS)

### Molly version

v7.8.1-2-FOSS

### Android version

Android 14

### Device

Pixel 8a

**Comment by valldrac** [comment]
Here are some steps to try:
- Free up space: make sure you have enough storage on your device
- Re-download: try downloading the APK file from GitHub and installing it directly

https://github.com/mollyim/mollyim-android/releases

Also, where did you install v7.8.1-2-FOSS from? And the update?
