### ISSUE TITLE
System theme changes not reflected in chats without screen reload

### ISSUE THREAD

**Issue by neunzehnachtneun** [mollyim/mollyim-android#358]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

There is a UI glitch introduced in 7.12.3-3 showing up in chats. The change of the dark mode switch is not recognized anymore in group and single chats, while it seems working in overview and settings.

### Steps to reproduce

1. Open a chat.
2. Switch dark mode on or off in Android settings.
3. See change isn't set in that chat.

### Molly version

v7.12.3-3-FOSS

### Android version

Android 14

### Link to debug log

https://debuglogs.org/android/7.12.3/f7cecbcc452a408a0afd39c7ba96bff7b4f67f95f56cec986ca4011d9f4e056f

**Comment by neunzehnachtneun** [comment]
Fyi. Filed an issue upstream, but got no answer yet.

https://github.com/signalapp/Signal-Android/issues/13654

**Comment by valldrac** [comment]
Can you try our latest version v7.26.1-1 beta? I think Signal has fixed the issue.

**Comment by neunzehnachtneun** [comment]
You are right. Its solved. Thanks!
