### ISSUE TITLE
SOCKS5 Proxy: DNS Fails, No Connection

### ISSUE THREAD

**Issue by 57194** [mollyim/mollyim-android#359]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

If I try to connect to a SOCKS5 proxy in Molly, the debug logs say all DNS fails. I'm able to connect Telegram and other apps to the SOCKS5 proxy in question with 0 issues, so this seems to be a Molly-specific problem.

### Steps to reproduce

1. Open Molly
2. **Settings** » **Network** » **Use proxy** » **SOCKS5**
3. Configure **Host** and **Port** to the same address that works for all my other apps/services using the SOCKS5 proxy in question
4. Click **Check connection** »» _Connection failed_ and debug logs show nothing but DNS failures.

### Molly version

v7.12.3-3-FOSS

### Android version

Android 14 (GrapheneOS)

### Device

Google Pixel 7a

---

Edit: Also: once this failure happens, I have to **Force stop** the app to get a connection back at all with no proxy.

**Comment by valldrac** [comment]
Thanks for the report. We just released a new beta version, v7.13.4-1. Could you give it a try and see if it resolves the issue with the proxy? Let us know how it goes.
