### ISSUE TITLE
Include UnifiedPush lib

### ISSUE THREAD

**Issue by iiitomo** [mollyim/mollyim-android#36]
I wish Molly allows me choose my distributor for Push Notifications. (e.g. so that I can use Gotify instead of FCM / Google services)

UnifiedPush is a recent FOSS library that allows this, I suggest to include it in Molly. 

See https://unifiedpush.org  and Matrix discussion #unifiedpush:matrix.org

**Comment by valldrac** [comment]
Hi. I read the website but I don't quite understand it. The Signal team decides which provider they use to send push notifications, on the server side.

**Comment by iiitomo** [comment]
Thx for your answer. Correct, I discovered that after I created this ticket. So pre-requisite is that Signal server allows it, means feature be implemented in Signal app, so I think we can close this ticket.
FYI:  https://community.signalusers.org/t/use-gcm-fcm-alternatives-for-notifications/10264
