### ISSUE TITLE
Unable to link device

### ISSUE THREAD

**Issue by AtiusAmy** [mollyim/mollyim-android#364]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

I recently resetup my mainSignal (7.16.4) on a new Android install (DivestOS, if it matters) and I tried to link it to Molly (On LineageOS and HyperOS, if it matters), however it just keeps spinning and not linking.

Potential useful info: The latest release of mautrix-signal has a similar issue (theirs said 409 Conflict) which they fixed on main. I wonder if this is related, maybe Signal changed up a few things in their linked device?

### Steps to reproduce

1. Install Molly
2. Set it up as a secondary device
3. Scan the QR code with the main device
4. It just keeps loading forever

### Molly version

v7.13.4-1-FOSS

### Android version

Android 14

### Device

Redmi Note 9 Pro, Xiaomi Mi Pad 5

**Comment by kastnerp** [comment]
Same issue here.

**Comment by cadecomposer** [comment]
yep same thing happening with trying to link my samsung tablet

**Comment by valldrac** [comment]
Thanks for reporting the bug! It should be fixed now. We're releasing v7.17.4-1 beta with the fix in the next few hours.
