### ISSUE TITLE
Remove Missing Google Play Services warning from Molly-FOSS

### ISSUE THREAD

**Issue by randomwithnoname** [mollyim/mollyim-android#379]
### Is there an existing request for this?

- [X] I have searched the existing issues

### Feature description

Remove Missing Google Play Services warning from Molly-FOSS as it's irrelevant and still shows even if you have Google Play Services

**Comment by valldrac** [comment]
Which warning are you referring to? Did you see it when you registered or later? There are several in the app related to Play Services, though they should be hidden in Molly-FOSS.

**Comment by randomwithnoname** [comment]
"This device is missing Google Play Services. You can still use Molly, but this configuration may result in reduced reliability or performance. If you are not an advanced user, are not running an aftermarket Android ROM, or believe that you are seeing this in error, please contact support@molly.im for help troubleshooting."

**Comment by randomwithnoname** [comment]
It shows when registering

**Comment by valldrac** [comment]
Thanks for letting us know. We used to hide it before, but our change got lost when Signal did a refactor of the registration screens.
