### ISSUE TITLE
Black screen camera P40-Pro

### ISSUE THREAD

**Issue by Imikeeee** [mollyim/mollyim-android#39]
Hi

The Molly camera not working on my Huawe P40-Pro.
Even the camera flip or the flash not working. 
When I go back o the chat , a text says : the camera not accessable or something in my language (so ints an android warning text)

**Comment by valldrac** [comment]
This is a known bug in Signal, see https://github.com/signalapp/Signal-Android/issues/9150

Can you comment on that thread your problem please? Looks like @yan796 has sent a pull-request to Signal that fixes it.

**Comment by Imikeeee** [comment]
I dont really know how github pulls works , so ima wait for you

**Comment by domportera** [comment]
I have this too on my LG V60. Signal works fine

**Comment by valldrac** [comment]
> I have this too on my LG V60. Signal works fine

It could be a different issue than this ticket. Can you please share the debug log next time you experience the problem? It's in Molly Settings > Help > Debug log and email to support@molly.im

**Comment by domportera** [comment]
oh sorry I didn't get back ! but the issue resolved itself 🤷‍♂️ idk how or when exactly but it mightve just needed a phone restart
