### ISSUE TITLE
7.26.x support

### ISSUE THREAD

**Issue by photoventures** [mollyim/mollyim-android#400]
### Is there an existing request for this?

- [X] I have searched the existing issues

### Feature description

Is there an ETA for supporting 7.26.x upstream Signal?

**Comment by BHydden** [comment]
> 7.26.x

It just came out 4 days ago...

 "We update Molly every two weeks to include the latest features and bug fixes from Signal. The exceptions are security issues, which are patched as soon as fixes become available."
 [Source](https://github.com/mollyim/mollyim-android#:~:text=We%20update%20Molly%20every%20two%20weeks%20to%20include%20the%20latest%20features%20and%20bug%20fixes%20from%20Signal.%20The%20exceptions%20are%20security%20issues%2C%20which%20are%20patched%20as%20soon%20as%20fixes%20become%20available.)
