### ISSUE TITLE
Add Unified Push for NextPush

### ISSUE THREAD

**Issue by ProfZiebart** [mollyim/mollyim-android#405]
### Is there an existing request for this?

- [X] I have searched the existing issues

### Feature description

I have a nextcloud instance running with nextpush Unified Push Service running. Is it possible to have push working that way to Molly? 
Then I would need a workaround the QR Code, as Nextpush does not show one.

**Comment by p1gp1g** [comment]
NextPush works fine. You need to scan [MollySocket](https://github.com/mollyim/mollysocket) QR code, your UnifiedPush distributor is still detected automatically. If you were using the -unifiedpush version before, it failed without a MS server (and fallback to the websocket) but the failure could be missed by users.

This is one of the reasons the QR code is a requirement now
