### ISSUE TITLE
Bug in unified push: looping re-registering

### ISSUE THREAD

**Issue by Menelmacar** [mollyim/mollyim-android#407]
##### _This is not a feature request, but I could not choose anything else when creating the issue._ 

Hi, I've installed mollysocket by downloading the binary and setting it up as per the install.md as systemd service.
I've freshly installed Molly Foss, and moved my data from signal. 
I'm using an apache2 reverse proxy. 
The service works and I get test notifications / push to Molly. 
The process is using i/o and cpu most of the time and the log is a constant stream of opening websocket to signal and closing again. I've attached all logs I could get, I can't interpret the molly android log myself. 

The connection stays stable for a while, often when I send or receive a message, thenit startsxconstantly opening and closing websockets again. 

The molly log I've attached is from a time where the websockets are constantly destroyed, at the end of thr log I send a message and it stopped for a while. 

prod.toml:
db = '/opt/mollysocket/mollysocket.db'
allowed_endpoints = ['https://mypushserver.de']
allowed_uuids =                                            ['b00cfa88-0e25-46ef-b26e-e88b7b0d1326']
webserver = true
port = 8020

Log:
[mollysocket-log.txt](https://github.com/user-attachments/files/18022870/2e3aa3f2-0d21-4678-976f-dc113069f362.txt)
debug log mollysocket:
[Mollysocket-debug.log.txt](https://github.com/user-attachments/files/18052560/log.txt)
Android Mollylog: https://github.com/user-attachments/files/18039531/06_12-15-36-30_229.log

Prosody mod_unified_push log:
[Prosody.log.txt](https://github.com/user-attachments/files/18047859/Prosody.log.txt)

I'm on Debian stable, mollysocket 1.5.4
Molly: v7.26.1-1-FOSS on CalyxOS on  Nexus7 Android 15
The push server is a prosody module, the distributor is my xmpp app conversations .

I've first submitted the issue in the push server repository, but I think this is a molly issue.

**Comment by Menelmacar** [comment]
It may be an issue with the prosody module, because if I use something else as push server the issue is gone.

**Comment by valldrac** [comment]
Adding #410 anyway to prevent this from happening.
