### ISSUE TITLE
Allow to ignore backup restore version mismatch

### ISSUE THREAD

**Issue by PalmTamino** [mollyim/mollyim-android#419]
### Guidelines

- [X] Yes, I have searched the existing requests

### Feature Description

So, I want to switch back to Molly, but since Molly is still on an older version, it says I cannot restore the backup.
I would like a feature that lets us disable this check, as in most cases, there are no breaking changes in the database anyway.

But of course, disable it st our own risk.

**Comment by valldrac** [comment]
What you're asking is not possible. SQL database migrations involve schema or data transformations, changes that are always breaking changes.
