### ISSUE TITLE
[Enhancement] Remove Freenode in README.md

### ISSUE THREAD

**Issue by taivlam** [mollyim/mollyim-android#48]
According to [the Register](https://www.theregister.com/2021/05/19/freenode_staff_resigns/) and other "real" internet/web reporting sites entities, there has been a hostile takeover of freenode.

A new Matrix/Element room (which doesn't bridge to freenode) has already been created.

* As a reference, GrapheneOS has already abandoned its 2 official Matrix rooms, that bridged with freenode, with two respective Matrix-only rooms.

(According to my understanding, freenode isn't an improper subset of IRC - i.e. literally all of IRC - though still a major IRC network.)

(Also, not sure if there are plans to make non-freenode IRC bridging still work or not - I don't know much about IRC bridging in Matrix/Element.)

**Comment by taivlam** [comment]
This is addressed by Pull Request #49.

**Comment by valldrac** [comment]
I merged your PR as-is while we decided how to support IRC again. For now the official chat room will be only on Matrix.

Thank you!

**Comment by haarp** [comment]
FWIW, the de-facto successor of Freenode is https://libera.chat.
