### ISSUE TITLE
DoH provider

### ISSUE THREAD

**Issue by kalekad** [mollyim/mollyim-android#50]
Would it be possible to add the option to set the DoH provider by user and add the option to disable DoH for proxies?

**Comment by valldrac** [comment]
OkHttp always performs DNS queries when a socks proxy is set. Although it shouldn't. We use DoH with the proxy as a workaround to prevent those leaks. We cannot disable it.

Can you describe please use cases for a configurable DoH?

**Comment by kalekad** [comment]
Thank you for the explanation.

I would like to route DNS queries to my VPN/proxy provider.

**Comment by valldrac** [comment]
> I would like to route DNS queries to my VPN/proxy provider.

I don't think any VPN vendors provide DoH endpoints.

Maybe there is a misunderstanding here. DoH is proxied too via SOCKS. So all DNS queries will be routed to your VPN always. They will no be replied by the VPN's DNS servers, that's true. But the source address of the queries will have the public IP of your VPN nodes anyway.

I'm closing this request now, but feel free to ask for further clarification.
