### ISSUE TITLE
Possibly very sensitive information can be retrieved with root.

### ISSUE THREAD

**Issue by 1Michael23** [mollyim/mollyim-android#52]
To preface this, i don't really know what I'm talking about, this might be nothing, but i would rather make sure.

With root access using the application App Manager to read the preferences for molly, the MasterKeys.xml file can be read/written to  even immediately after a reboot while molly database encryption is still enabled and locked

![molly-masterkeys](https://user-images.githubusercontent.com/33250781/121273290-74423b00-c8b7-11eb-9df0-6dc29a254ee7.jpeg)

I simply do not know what risk this poses if any, so i thought i would submit this to be safe.

**Comment by 1Michael23** [comment]
To add some extra information, I completely uninstalled app manager to make sure nothing was cached from when molly was unlocked.

the other preferences that can be read are: 

- im.molly.app.xml
- MasterKeys.xml
- SecureSMS-Preferejces.xml 
- com.google.android.gms.appid.xml
- FirebaseAppHeartBeat.xml

**Comment by valldrac** [comment]
There's no sensitive information leaked there.

The master_secret keys in MasterKeys.xml are encrypted with molly passphrase. And the other values are not confidential, only needed to setup the encryption.

The entries in "SecureSMS-Preferences.xml" and "im.molly.app.xml" are encrypted as well with molly passphrase. Read the files and check it by yourself. All are cipher-texts unless the language and theme preferences, that are required to show the passphrase prompt and so they cannot be protected by the passphrase.

FirebaseAppHeartBeat.xml and com.google.android.gms.appid.xml are handled by Google's FCM library and has no confidential information.
