### ISSUE TITLE
For more security spongycastle -> bouncycastle

### ISSUE THREAD

**Issue by Neustradamus** [mollyim/mollyim-android#6]
For more security, can you change old spongycastle (based on old bouncycastle) to bouncycastle?
- https://www.bouncycastle.org/
- https://www.bouncycastle.org/releasenotes.html
- http://www.bouncycastle.org/latest_releases.html
- https://www.cvedetails.com/vulnerability-list/vendor_id-7637/Bouncycastle.html

**Comment by valldrac** [comment]
Signal and Molly replaced spongycastle by conscrypt as default security provider one year ago, with the release of libsignalservice v2.13.0.

**Comment by Neustradamus** [comment]
@valldrac: Thanks for your reply!
But there is: https://github.com/mollyim/mollyim-android/search?q=spongycastle&unscoped_q=spongycastle...
Can you solve it?

**Comment by Neustradamus** [comment]
@valldrac: Thanks :)
