### ISSUE TITLE
Open unencrypted lock when sending encrypted message

### ISSUE THREAD

**Issue by mollyuser** [mollyim/mollyim-android#63]
I often have an open lock icon when sending molly message. This mean it s unencrypted dont know whats wrong.

**Comment by mollyuser** [comment]
So to explain myself better, when i send a message and pres send, there comes a circle that is going round and a small open lock, and that the delevired bubbeles come and the open lock dissapears. This doesnt happen with every mesaage, just now and than.

**Comment by valldrac** [comment]
It is a glitch in the user interface with zero impact in the security. The unlocked icon is for SMS messages only, and Molly cannot send SMS.

But I cannot remove the icon because Molly can import SMS chats from Signal backups. I'll try to fix this for the upcoming release.

**Comment by valldrac** [comment]
Reported to Signal in https://github.com/signalapp/Signal-Android/issues/11488.
