### ISSUE TITLE
Backup is not restored correctly, only group membership is preserved

### ISSUE THREAD

**Issue by aosar** [mollyim/mollyim-android#64]
I have a Signal backup from v5.18.5 trying to transfer to Molly v5.16.3-2 .

I imagine the backups should be compatible, but it may not be given the problem I'm having. I've gone through the process to restore from a Signal backup file and got no errors, but I have none of my messages restored. I was not prompted for my passphrase, only my signal pin. I do however, have group chat membership restored. It simply says I've joined the group chats without any of the messages recovered. 

Extra info:
- My backup file is >1GB
- I'm using Samsung Galaxy s10e

Let me know if you need any other information. 
Thank you in advance!

**Comment by valldrac** [comment]
Thanks for the report.

The group chat membership are restored with the Signal PIN. This is not an indicator that the backup was restored successfully. Moreover, the backup cannot be read without providing the backup passphrase to the app.

I guess the backup file was not processed for some reason (it's corrupted maybe?) and thus the messages are missing.

You can share the debuglog after a failed backup restoration to help me to debug it.

Unfortunately, Signal and Molly sometimes generate broken backup files.

**Comment by johanw666** [comment]
Did the group have expiring mesages on? Those are deliberately not included in a backup.

**Comment by clauz9** [comment]
@aosar  did you manage to restore you back-up ? if not, can you please tell us the Android version you're using ?

**Comment by aosar** [comment]
@johanw666 Sorry for the belated response. Some groups had expiring messages at times, but some messages were permanent. Permanent messages were not restored.

@clauz9 I was not able to restore my backup. My OS and Signal have updated since I last attempted this, but I can give it another go. I can update with further information.

**Comment by clauz9** [comment]
@aosar sure, give it another try and let us know if it works, but  do you know what android version you were on before it updated ?
