### ISSUE TITLE
Black/Oled Chat headers/bubbles

### ISSUE THREAD

**Issue by Sn0whax** [mollyim/mollyim-android#7]
Hi,

Thanks for adding the OLED theme! loving it! (I submitted the original request for an OLED black)
Would you mind adding a chat color? 

- Having an Oled black chat/header for a specific people would be amazing.
- Having it an Oled black header for the group chats would also be great. I understand this is more difficult?

**Comment by valldrac** [comment]
I'd like to solve the general problem instead. My idea is to add a custom color picker for chats and groups, along with the predefined set of colors. Does make sense?
