### ISSUE TITLE
[Feature Request] Add Monero URI/address support

### ISSUE THREAD

**Issue by sethsimmons** [mollyim/mollyim-android#70]
It would be great to see Monero URI and/or address support so that when a user receives a Monero address/subaddress or Monero URI, they can click it to open that address/URI in a mobile wallet like Cake Wallet or Monerujo.

URI formatting details can be found here: https://github.com/monero-project/monero/wiki/URI-Formatting
Address details can be found here: https://www.getmonero.org/resources/moneropedia/address.html

**Comment by valldrac** [comment]
Done. Will be available in the upcoming release.

**Comment by sethsimmons** [comment]
Wow, that was fast! Thanks so much!
