### ISSUE TITLE
when having 2 molly instances (through Island Personal and Work Profiles) the work molly will work only with the Personal profile passpharse

### ISSUE THREAD

**Issue by natur960** [mollyim/mollyim-android#72]
when having 2 molly instances (through "_Island_" Personal and Work Profiles) the _work_ molly will accept the _Personal_ profile molly passpharse and nothing else . I can enter both and both of them accept only the personal profile passpharse .
(im using custom rom e os but dont think it matters much )

could not attach screenshots as those are passpharses :)

**Comment by valldrac** [comment]
Did you change the Molly passphrase in the work profile? Because it could break the personal instance.

Try the following instead:

1. Uninstall both apps
1. Install Molly in the personal profile but don't start it
1. Clone it to work profile
1. Proceed with the registration as usual

**Comment by natur960** [comment]
i think something in the memory is not handled right and that is the reason . there's not complete seperation between work molly and personal molly -ive tried running work molly after force stopping both instances then at some cases it will personal molly instead of work molly that ive intented to - when that happened i also tried greenifying work signal that was also installed and then work molly was running.

so maybe its possible to add a check in the begining if signal of the same profile is runing and let the user stop it ?

**Comment by natur960** [comment]
update - its not stable:
ive greenified personal molly,  work molly , work signal
made sure all 3 of them are force stopped .
then when i run work molly from island list then it would run at some points the personal molly , and at some other cases the work molly. there's something more involed that im not sure that pointing work molly to persnal molly. maybe some memory issue.

**Comment by natur960** [comment]
however - when ive changed the passpharse under settings then it would accept the new passpharse of the work molly as it should. and the personal molly will accept its own passpharse - as it should. 

but something with the running of work molly is not right.

**Comment by valldrac** [comment]
If the steps I told you didn't work, I'm afraid the Island app isolation is completely broken for complex apps like Signal and cannot be helped.

Maybe you would like to join our Matrix room and ask for help to the Molly community.
