### ISSUE TITLE
Molly not connecting to server (while Signal is able to)

### ISSUE THREAD

**Issue by encrus** [mollyim/mollyim-android#73]
I am getting an issue with Molly not connecting. I get the message pls see screenshot below.
At the same time Signal installed on the same phone is connecting fine. 

I upgraded to the latest version of molly but I see same issue of not connecting. After a minute or so it asked to reregister but that too didn't work because of connection issue. 
Don't molly and signal use the same server. I guess so, so there may be some issue or bug with the Molly code ?

![MollyNotConnectingIssue1](https://user-images.githubusercontent.com/16273760/134861331-a159b2ea-0dcc-4019-93cb-43400920d485.jpg)

**Comment by valldrac** [comment]
There was a network outage https://twitter.com/signalapp/status/1442354759009247232. 

Until fully recovered, Molly and Signal might behave differently. One could connect and the other could not yet.

**Comment by encrus** [comment]
Actually the issue is that it asked me to complete registration (upon upgrade of app). But it doesn't connect then at all.
