### ISSUE TITLE
Request: support Unified Push for notifications

### ISSUE THREAD

**Issue by strider72** [mollyim/mollyim-android#74]
feature request: Molly should support Unified Push (UP)

https://UnifiedPush.org

https://github.com/UnifiedPush

Allows for notifications through a single remote server (that is NOT Google), without per-app open connections draining battery.

UP is FOSS, so could be included in Molly FOSS. Even non-FOSS Molly could support it so people who aren't running GSF can use it.

It's flexible in that it allows the user to choose what server notifications pass through:

1. Self hosted (anywhere you like/ custom)
2. UP offers hosting
3. Google notifications (seems self defeating, but it isn't. Google gets much less information because all they see are UP notifications even if it's passing along for a dozen different apps)
4. No server at all, via static IP
5. Whatever else somebody might think of, via plugin architecture

**Comment by strider72** [comment]
Sigh. Never mind. It's up to the servers, which are Signal's

**Comment by genofire** [comment]
How does it work with FCM current? The Server has not the token of this app ...

Does a extra Push Gateway run here? If yes, UnifiedPush should also BR possible.
