### ISSUE TITLE
SMS for Molly?

### ISSUE THREAD

**Issue by PLAYERUNKNOWNHatsune01** [mollyim/mollyim-android#79]
Will Molly support SMS to like Signal? I want to Molly to have SMS too so I don't have to install other sms app again to my phone. and with Molly Local Encryption it would be nice to have sms in it and get protected even though it just on user device. Hope Molly get sms too like Signal in near future

**Comment by DigitalNXZ** [comment]
Probably not~
#8 #15

**Comment by PLAYERUNKNOWNHatsune01** [comment]
ohh kinda sad
