### ISSUE TITLE
Auto Lockdown Triggers Immediately

### ISSUE THREAD

**Issue by DevinCharles** [mollyim/mollyim-android#80]
I have auto lockdown set 36 hours, but the app locks immediately. This seems to be a bug that popped up in the last few updates, as it was previously working.

**Comment by valldrac** [comment]
Can you share the debug log please? When it happened, start Molly and go to Settings > Help > Debug log > Submit. Then tap and hold to copy the URL and copy here.

Also it could be the app stops for other reason not related to lockdown. Did you see the wipe service starting just when it locked? It displays a progress bar in the notification area while it's running.
