### ISSUE TITLE
heating issue samsung A51

### ISSUE THREAD

**Issue by bangla161971** [mollyim/mollyim-android#81]
when I open app its starting heating on screeen plz slove this problem 
https://debuglogs.org/2c64cf5a5ba44f9ca8fbba4ea5d4ef673dd51d4ea7f0a162f5451790f650050a foss apk

https://debuglogs.org/a8fd7aa6a768ebed34e186032afc32839dbcc486cc4afdd5a4794bbca0a98a56 apk github

Samsung A51
android11
one ui 3.0

**Comment by valldrac** [comment]
This ticket is from a really old version. This bug is already fixed.
