### ISSUE TITLE
App immediately crashes in Android x86 emulator

### ISSUE THREAD

**Issue by mstyp** [mollyim/mollyim-android#84]
I am running android x86 in virtualbox.  android version 9. I tried downloading the apk from github and from fdroid. no difference, app crashes straight away.  i dont think its a memory issue, virtual machine allocated 7884 MB of ram and 3 CPUs, but must admit virtualizing android is kind of slow / janky but unsure if related. 

regular signal app starts fine on this virtualbox android device. I just want to register a new account so I can setup a new linked desktop client, but moxie is a jerk and deliberatly chose to not allowing linking accounts without a camera, despuite even the crappiest of android devices costing several thousands of dollars where I live.

**Comment by valldrac** [comment]
Molly dropped the support for ABI x86. Ensure you're using a x86_64 Android emulator.
