### ISSUE TITLE
Anyway to change Molly launcher icon?

### ISSUE THREAD

**Issue by InvisibleMan101** [mollyim/mollyim-android#85]
Hi,
I just wanted to know if you wanted to hide the fact you were using signal/molly from an adversary unfortunately if you go into settings on the phone once it is opened up and look at apps in android you can see the app icon. For some people that wish to edit this how is this possible so that the launcher icon can be disguised as something else without having to install an app that simply creates a shortcut to the home screen?
Thanks

**Comment by Seb3thehacker** [comment]
You can install a custom launcher. The one I like is called Lawnchair launcher. You can set the icon to anything you want.

**Comment by valldrac** [comment]
Thank you @Seb3thehacker for the suggestion.

**Comment by InvisibleMan101** [comment]
> You can install a custom launcher. The one I like is called Lawnchair launcher. You can set the icon to anything you want.

Thanks for the reply but this needs to be done on a deeper level because the icon does not change in app settings or when you open the app. Programming wise where is this ability within the code?

I tried to do this with APK editor with no luck.

**Comment by Seb3thehacker** [comment]
You can build the app with your own icon using Android Studio. You could probably change it by rooting your device also.
