### ISSUE TITLE
Wrong translation license?

### ISSUE THREAD

**Issue by comradekingu** [mollyim/mollyim-android#87]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

https://hosted.weblate.org/projects/molly-instant-messenger/molly-app/#information https://hosted.weblate.org/projects/molly-instant-messenger/glossary/#information
are both GPLv3-only, wheras

https://github.com/mollyim/mollyim-android/search?q=or+later
says GPLv3-or-later

The license can be changed in
https://hosted.weblate.org/settings/molly-instant-messenger/molly-app
 https://hosted.weblate.org/settings/molly-instant-messenger/glossary/

### Steps to reproduce

1.
2.
potato

### Molly version

0.0.0

**Comment by valldrac** [comment]
I've changed the translation licenses to GPLv3-or-later :+1: Thanks for notifying us.
