### ISSUE TITLE
Use Unified Push as Push Provider

### ISSUE THREAD

**Issue by schnuppikarotti** [mollyim/mollyim-android#88]
### Is there an existing request for this?

- [x] I have searched the existing issues

### Feature description

Would be a nice feature for the FOSS-Version to Support https://unifiedpush.org

**Comment by p1gp1g** [comment]
FYI, I am using molly with UnifiedPush for a month now. It requires a software running on a server. (The server does not have any crypto key, so the encryption is not broken)

I will give more details, publish the server code and open a PR for Molly as soon as it is ready for testing. Then some testers will be very welcome. Also that the first time I write some rust, any rust reviewer will be welcome too :)

**Comment by genofire** [comment]
hmm, have not write much in rust and have not much time.

I will host an server (in my k8s), after i build an container and helmchart.

**Comment by ilikenwf** [comment]
> FYI, I am using molly with UnifiedPush for a month now. It requires a software running on a server. (The server does not have any crypto key, so the encryption is not broken)
> 
> I will give more details, publish the server code and open a PR for Molly as soon as it is ready for testing. Then some testers will be very welcome. Also that the first time I write some rust, any rust reviewer will be welcome too :)

Any news on this? Sounds interesting and a lot less convoluted than using Matrix...

**Comment by p1gp1g** [comment]
It can now (*) begin to be reviewed and tested.  It still misses a few things (like replacing the shared preferences by the internal store, implementing alerts for edge cases for a specific setup and adding readmes) but this can be done during the tests and review.

(*) I will very probably publish everything this week

**Comment by ilikenwf** [comment]
Very cool!

Have you done any battery benchmarking between push vs websocket?

**Comment by p1gp1g** [comment]
Not really, I do not have a lot of contact on Signal so it is not very relevant. Also, I have only tested one of the 2 fetch strategies implemented. That's why testers are very welcomed: we should compare the battery consumption with the 2 strategies and without UnifiedPush (with FCM or with the websocket).

**Comment by julianfoad** [comment]
Just a note that activity on this is taking place in the linked merge request #152 . We can follow it there. (Hurray!)

**Comment by valldrac** [comment]
This is already done. Officially supported since version 6.35.3-1.

**Comment by ilikenwf** [comment]
> This is already done. Officially supported since version 6.35.3-1.

Oh so it's in the mainline apk now? The wiki/readmes need updated to indicate this if possible as they still imply there are separate builds for it on fdroid.

**Comment by valldrac** [comment]
> Oh so it's in the mainline apk now?

Not yet. But it's fully supported with the separate apk in https://github.com/mollyim/mollyim-android-unifiedpush. We'll have it all in one app at some point.

Just found this old ticket and closed it.

**Comment by ilikenwf** [comment]
I switched back to molly recently, just with websockets...while bat usage is higher I was sick of gsf under graphene.

**Comment by valldrac** [comment]
> I switched back to molly recently, just with websockets...while bat usage is higher I was sick of gsf under graphene.

We made some improvements to reduce battery drain in the latest update: https://fosstodon.org/@mollyim/111816064499180353
