### ISSUE TITLE
Is there interest in rewriting parts of the app in Kotlin?

### ISSUE THREAD

**Issue by Zanthed** [mollyim/mollyim-android#90]
### Is there an existing request for this?

- [X] I have searched the existing issues

### Feature description

Android is pushing for apps to be made/rewritten/ported to Kotlin and modern apps should consider using Kotlin.

Kotlin can obviously be ported in small increments and you can call normal Java code in Kotlin to help ease the porting process.

But is there any interest in porting core Signal stuff to Kotlin downstream? What about upstream's opinions on it?

**Comment by valldrac** [comment]
Kotlin is now the preferred language for the Signal team, and in Molly as well. Personally I like Kotlin. Some core modules have been written in Kotlin already and up to 15% of code base is Kotlin.

**Comment by Zanthed** [comment]
That's good to know! Would you accept pull requests to downstream Java -> Kotlin?

**Comment by valldrac** [comment]
There is little benefit to simply converting Java source code to Kotlin without actual taking the opportunity to refactor the code. Also, I have to stay close to upstream original code to reduce merge conflicts.

You can ask the Signal team too. Although historically they have never accepted such contributions.
