### ISSUE TITLE
Chat notfications aren't shown as conversations when database encryption is on

### ISSUE THREAD

**Issue by d3l4m41n** [mollyim/mollyim-android#93]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

When the database encryption is not enabled, android treats chat notifications as an 'conversations'. If database encryption is enabled and the databse unlocked chat notifications are ’normal’ notifications instead of a 'conversation'.

### Steps to reproduce

1.Enable database encryption
2.Receive a message
3.View notifications

### Molly version

v5.31.6-1-FOSS

### Android version

Android 12

### Device

Google Pixel 4 XL

**Comment by clauz9** [comment]
you need to explain this a bit more, what exactly happens ? 
Normally you shouldn't be getting any notifications when database encryption is enabled.

**Comment by d3l4m41n** [comment]
Android has 3 '_sections_' in which notifactions can be devided: silent, '_normal_' and conversations. If the database within Molly is not encrypted notifications for new messages appear as conversation notifications. If the database is encrypted (and of course unlocked, so Molly can receive messages) new messahes appear as '_normal_' notifications. Conversation notifications can also be marked as priority, making them during DnD etc.
Hope this clarifies it

**Comment by clauz9** [comment]
I tried to replicate this on a Samsung A10 with Android 11, 🤔  the notifications were always the same, no matter if the database encryption was enabled or not 🤔 
you probably should attach some screenshots, and a log, or send them privately.

**Comment by d3l4m41n** [comment]
From https://developer.android.com/guide/topics/ui/conversations#api-shortcuts
> In order to participate in this conversation-centric initiative, apps need to provide the system with long-lived shortcuts

Molly cannot clear Shortcuts/Conversations in a reliable way before locking. When Molly has passphrase encryption enabled and it's locked, there shouldn't be any leaks, so the use of Shortcuts/Conversations is not compatible with Molly's current thread model.

**Comment by ilikenwf** [comment]
Question: is this related to why when using molly without encryption on the DB, I still can't do quick replies? The OS already allows control of whether or not content that is sensitive is shown both on the lock screen and unlocked context, so I'm wondering why quick replies and message content are disabled without a toggle in Molly.
