### ISSUE TITLE
Please add screen lock/unlock option using device fingerprint(Biometrics)

### ISSUE THREAD

**Issue by aravind-alpha07** [mollyim/mollyim-android#94]
### Is there an existing request for this?

- [X] I have searched the existing issues

### Feature description

Passphrase encryption is a very useful feature thank you. but during traveling or using mobile in one hand it's not handy to enter the passphrase every time so please add unlock with biometric as an optional additional feature

**Comment by hj-collab** [comment]
+1. Biometrics is essential. It is also useful in public places with cameras. Only reason holding me back from using Molly.

**Comment by clauz9** [comment]
> It is also useful in public places with cameras. Only reason holding me back from using Molly.

this is not going to work the way you probably want it to work ... you will still need to type the database encryption passphrase, in "public places with cameras" 

and if you're concerned about cameras ... a privacy screen protector is probably a better investment
