### ISSUE TITLE
Wrong apk in Molly-FOSS repo

### ISSUE THREAD

**Issue by realmebran38** [mollyim/mollyim-android#98]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

The v5.32.15-1  apk in molly.im/fdroid/foss/fdroid/repo is dependent on Google Play Services.

PS: Your FOSS efforts are very valuable. Thanks a lot...

### Steps to reproduce

I have a device without play services (clean Lineage OS - pixel 2 walleye);  installed FOSS apk from molly.im/fdroid/foss/fdroid/repo (via Fdroid app using repo). This installed according to GUI Fdroid app the version: 5.32.15-1 (latest). But I got "notification" Molly was unable to register with Google Play services.

So I installed the apk manually from https://github.com/mollyim/mollyim-android/releases/tag/v5.32.15-1
Molly-v5.32.15-1-FOSS.apk

Problem resolved.

Test:

```
$ md5sum *apk
c12568cf47458701a118407d936dbd2f  im.molly.app_101800.apk
bca1aa488cf41338ce796e89b01978e3  Molly-v5.32.15-1-FOSS.apk
```

### Molly version

v5.32.15-1-FOSS

### Android version

Android 10

### Device

Pixel 2

**Comment by Seb3thehacker** [comment]
I messed up the hashes on my end. Sorry everyone. Going to be well slept from now one before contributing.

**Comment by realmebran38** [comment]
Could I ask why this was marked as invalid?

**Comment by valldrac** [comment]
> Could I ask why this was marked as invalid?

We did the follow-up in the Molly Matrix room and there was no issue. The APKs in the repo are correct. It was a mistake by the reporter hashing one APK from a different project. Read the previous comment from him.
